### ISSUE TITLE
Tooltip not working for all points

### ISSUE THREAD

**Issue by abayomiAkanji** [syncfusion/flutter-examples#112]
Tooltip only works for the first point/axis in the charts. How can I make it work all points clicked?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @abayomiAkanji ,

Thanks for your interest in Syncfusion Flutter widgets. We have analyzed the reported scenario and tries to replicate. But, we cannot replicate the reported scenario at our end with our current version 18.1.43. However, We have attached a simple sample which we have used for testing. Kindly, ensure with the provided sample if the issue is replicating on your side.

The sample for reference can be found below.
[tooltip1.zip](https://github.com/syncfusion/flutter-examples/files/4468499/tooltip1.zip)

Since we are not aware of the exact scenario, kindly revert us with more information about your scenario with some samples or some screenshots. This will be helpful in providing the solution earlier.

Thanks,
Sriram Kiran
