### ISSUE TITLE
Legend series colors wrong when pointColorMapper used

### ISSUE THREAD

**Issue by jfox454** [syncfusion/flutter-examples#114]
When the pointColorMapper is used to change the color of a series, the Legend color is not updated and still appears to use the Color Palette colors.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @jfox454 ,

 

Greetings from Syncfusion. We have analyzed your scenario at our end. As of now, the default behavior in cartesian chart is when the point color mapper is used, it doesn’t change the legend color. The circular and triangular chart only have that kind of feature. Can you provide us more information on what type of chart widget are you using? So, that we can provide a solution for your requirement at earlier.

 

Thanks,

Sriram Kiran

**Comment by jfox454** [comment]
Hi @SriramKiranSenthilkumar ,
I am using the SfCartesianChart widget. 
Thanks
Jack

**Comment by SriramKiranSenthilkumar** [comment]
Hi @jfox454 ,

As of now, in the cartesian chart widget, the legend colour can't be changed according to the point colour mapper values, since the legend is created for the series only and not for the individual data points of that series. So, this is the default behaviour of the legend in the cartesian chart widget.

Thanks,
Sriram Kiran.

**Comment by jfox454** [comment]
Are there any plans to update this behaviour so that the legend color is set by the point color mapper for a cartesian chart?

My preference would be to use the point color mapper rather than having to adjust the color palette for each chart.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @jfox454 ,

No, the legend colour in the cartesian chart is currently set according to the series colour palette prescribed in the chart. This is the default behaviour of the legend as mentioned earlier. It cannot be changed according to the point colour mapper values of the data points because for every individual series in the chart, a single legend is created. For example, we have created a simple sample and provided the screenshot below to explain the behaviour. We have provided two series in the chart in which one series has point colour mapper values mapped for the data points and another series with no pointColorMapper values mapped and with legend enabled for both the series. You can see that for each series in the chart one legend is created. So, it is not possible to map the point colour for the series legend which has point colour mapper mapped to individual data points.

**Screenshot:**

![image](https://user-images.githubusercontent.com/63577117/80229928-cd78ec00-866e-11ea-8cbe-776cf756fb28.png)

The sample for reference can be found below
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4529880/sample.zip)

You can customize the legend colour for each series individually using the onLegendItemRender event available in the chart. Please refer the below code snippet to achieve it.
```
SfCartesianChart(
          onLegendItemRender: (LegendRenderArgs args) {
            if(args.seriesIndex == 1) {
              args.color = Colors.yellow;
            }
          },
)
```

For further reference on onLegendItemRender event, please check the user guide below
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onlegenditemrender

Thanks,
Sriram Kiran.
