### ISSUE TITLE
StackedLineSeries Incorrect Values on SfCartesianChart

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#115]
Using syncfusion_flutter_charts: ^18.1.44

I created series data that should overlap two lines on one plot:

```
var series = <CartesianSeries<ChartSampleData, DateTime>>[
      StackedLineSeries<ChartSampleData, DateTime>(
          dataSource: spendingThisMonthChartData,
          xValueMapper: (ChartSampleData data, _) => data.x,
          yValueMapper: (ChartSampleData data, _) => data.yValue,
          legendItemText: 'This Month',
          color: primaryTextColor,
          animationDuration: 0,
      ),
      StackedLineSeries<ChartSampleData, DateTime>(
          dataSource: spendingLastMonthChartData,
          xValueMapper: (ChartSampleData data, _) => data.x,
          yValueMapper: (ChartSampleData data, _) => data.yValue,
          legendItemText: 'Last Month',
          dashArray: <double>[5, 5],
          color: tealSoft,
          animationDuration: 0,
      )
    ];
```

When I give the series data to an SFCartesianChart, the chart visually shows incorrect y values for Last Month, but This Month appear correct visually. The Last Month spending is only incorrect when I have both lines stacked at the same time. If I disable This Month by pressing it in the legend, the y values for Last Month become visually correct.

This shows both lines plotted at once (where This Month is correct and Last Month is incorrect):
![image](https://user-images.githubusercontent.com/50309714/79680241-6a550880-81db-11ea-822e-b7536887906f.png)

This shows only Last Month plotted, and these are the correct values. This Month is disabled by pressing the legend item:
![image](https://user-images.githubusercontent.com/50309714/79680255-aa1bf000-81db-11ea-8385-e39bc79a6703.png)

These are the correct values for Last Month:
```
amount: 4000.0, dateTime: 2020-04-01 00:00:00.000
amount: 4715.2, dateTime: 2020-04-12 00:00:00.000
amount: 4845.84, dateTime: 2020-04-13 00:00:00.000
amount: 5473.84, dateTime: 2020-04-14 00:00:00.000
amount: 60273.84, dateTime: 2020-04-15 00:00:00.000
amount: 60517.03999999999, dateTime: 2020-04-16 00:00:00.000
amount: 85145.04, dateTime: 2020-04-25 00:00:00.000
amount: 89145.04, dateTime: 2020-04-26 00:00:00.000
amount: 89195.68, dateTime: 2020-04-29 00:00:00.000
amount: 93195.68, dateTime: 2020-05-01 00:00:00.000
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @opalr ,

Greetings from Syncfusion. We have analyzed your scenario at our end. We would like to let you know that in the stacked series the y values get stacked one over another i.e., the y values of the stacking series get added cumulatively added with the previous series and gets rendered. For example, you have two series in the chart in which the first series has y-values say y(1,2,3,4,5) and the second series has y-values say y(1,2,3,4,5). While rendering the second series values get cumulatively added with the first series values and gets plotted on the chart. After rendering the y-values of the series will be series-1-y(1,2,3,4,5) and series-2-y(2,4,6,8,10). However, for your case where you need to overlap two lines on one plot. So, you can use the line series instead of the stacked series. Please refer the sample below to achieve this.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4503487/sample.zip)

Thanks,
Sriram Kiran.
