### ISSUE TITLE
Custom color for every label item?

### ISSUE THREAD

**Issue by koteezy** [syncfusion/flutter-examples#119]
Hello!

I know how to use different color for every line:
```pointColorMapper: (_ChartData sales, _) => sales.lineColor```

But how use different color for every dataLabel?

I found only how to specify color for all of them, but not for selected.

```
dataLabelSettings: DataLabelSettings(
 isVisible: true,
 useSeriesColor: true,
 color: Colors.blue,
 textStyle: ChartTextStyle(color: Colors.white),
 labelAlignment: ChartDataLabelAlignment.top
)
```

I tries something like that:

```
onDataLabelRender: (DataLabelRenderArgs e) {
 LineSeries<_ChartData, DateTime> series = e.series;

 series.dataLabelSettings.color = Colors.red;
},
```

But i can't set color, because color property is final.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @koteezy ,

Greetings from Syncfusion. We have analyzed your scenario at our end and we have created a simple sample in order to provide a different colour for every data label using the onDataLabelRender event available in the chart. Please refer the code snippet below.
```
SfCartesianChart(
      onDataLabelRender: (DataLabelRenderArgs args) {
                  args.textStyle.color = chartData[args.pointIndex].color;
       },
)
```
**Screenshot**:
![image](https://user-images.githubusercontent.com/63577117/80695499-9fbef780-8af3-11ea-9fee-06d512a1c6f3.png)

The Sample for reference can be found below
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4557432/sample.zip)

For further reference on onDatalabelRender event, please check the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#ondatalabelrender

Thanks,
Sriram Kiran.

**Comment by koteezy** [comment]
>                   args.textStyle.color = chartData[args.pointIndex].color;

Thanks for reply, you'r code will change text color, not for background ( DataLabelSettings.color ), 
i can change only text color?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @koteezy  ,

We have analyzed your scenario and currently, we do not have support for providing different background colours for different data labels. We have considered as a bug and will include the fix for the reported scenario in the upcoming vol 1 SP1 release which will be rolled out in the middle of May 2020. We will update you once the release is rolled out. We appreciate your patience until then.

Thanks,
Sriram Kiran.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @koteezy ,

Thanks for your patience. The reported issue regarding the customizing the background colour for every data label in the chart is fixed and rolled out in Vol 1 SP1 release. So, kindly please upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.52

For Customizing the background colour of each data label using the onDataLabelRender event available in the chart, refer the code snippet below.
```
SfCartesianChart(
    onDataLabelRender: (DataLabelRenderArgs args) {
                  args.color = chartData[args.pointIndex].color;
                },
)
```
**screenshot:**
![image](https://user-images.githubusercontent.com/63577117/82055754-9a120600-96de-11ea-8444-a15fc898241b.png)

The Sample reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4634666/sample.zip)

Regards,
Sriram Kiran.
