### ISSUE TITLE
Format y-axis numbers as thousands or millions

### ISSUE THREAD

**Issue by mithunadhikari40** [syncfusion/flutter-examples#120]
First of all I want to thank you guys for this wonderful library. I am using this to display some bar chart and **I am wondering if there is any possibility for showing numbers in y-axis in a formatted way. For example:
16432 => 16K
1,000,000 => 1.00M
1,234,567 => 1.23M.**

Here is a snapshot of the code I am using.

```
<BarSeries<ReportDataModel, String>>[
      BarSeries<ReportDataModel, String>(
          enableTooltip: true,
          dataSource: targetList,
          xValueMapper: (ReportDataModel sales, _) => sales.objectName,
          yValueMapper: (ReportDataModel sales, _) => sales.value,
          name: AppLocalizations.of(context).Total_Sales),
      BarSeries<ReportDataModel, String>(
          enableTooltip: true,
          dataSource: quantityList,
          xValueMapper: (sales, _) => sales.objectName,
          yValueMapper: (sales, _) => sales.value,
          name: AppLocalizations.of(context).target),
    ]

```

Here in the yValueMapper is there any way to show sale.value as formatted string  like 16K or 1.23M rather than the actual numbers like 16000 or 1230000

Thank you.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @mithunadhikari40 ,

Thanks for your interest in Syncfusion charts. We have analyzed your scenario and we have created a simple sample in order to format the axis labels from showing numbers to compact representations using the **numberFormat** property available in the axis. Please refer the code snippet below.
```
SfCartesianChart(
            primaryYAxis: NumericAxis(
              numberFormat: NumberFormat.compact()
            ),
)
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/63577117/80958079-0c9efe00-8e22-11ea-8324-073bdcd6e36a.png)

And, also for formatting the axis labels with two decimal digits in compact representation, please refer the code snippet below to achieve it.
```
SfCartesianChart(
            primaryYAxis: NumericAxis(
              numberFormat: NumberFormat.compactCurrency(
                symbol: '',
                decimalDigits: 2
            ),
)
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/63577117/80958158-2e988080-8e22-11ea-88ae-bbd6e1730e7f.png)

The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4574137/sample.zip)

Thanks,
Sriram Kiran.

**Comment by mithunadhikari40** [comment]
@SriramKiranSenthilkumar Thank you so much. This is exactly what I need. You guys are the best. I am going to close this issue.

**Comment by mmgunes** [comment]
thank you @SriramKiranSenthilkumar 👏🏼👏🏼👏🏼👏🏼👏🏼
