### ISSUE TITLE
SfCartesianChart legend width

### ISSUE THREAD

**Issue by PHPadawan** [syncfusion/flutter-examples#123]
Hello,

i wonder why the width of the legendItemBuilder does not match the width of the diagram(red square in the picture). Is there a special reason for this? For space reasons it would be better to use the whole width. Unfortunately I could not find the exact place where this calculation is done.

<img width="364" alt="e26d6e3c6a980ebbe169a7890df75eb4" src="https://user-images.githubusercontent.com/12775942/81563321-665d7600-9396-11ea-9ce8-008697906aa0.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @PHPadawan ,

Greetings from Syncfusion. We have analyzed your scenario at our end and first, we want to clarify why the width of **legendItemBuilder** does not match the width of the diagram. This is because for example, if the width of the diagram is around 1000 pixels and if the width of the **legendItemBuilder** depends on the width of the diagram then the space between the legends will be large and thus looks bad while rendering. So only we have provided default padding values for the legends in our chart widget.

In order to change the padding values for the legends, you can use the **padding** property of the legend available in the chart. Please see the code snippet below for reference.
```
SfCartesianChart(
            // Enable legend
            legend: Legend(
               isVisible: true,
               padding: 10, // To add padding for the legends.
            )
)   
```
The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4615931/sample.zip)

Regards,
Sriram Kiran.

**Comment by PHPadawan** [comment]
Hi @SriramKiranSenthilkumar,

I don't quite understand why you cut the width for the legendItemBuilder when you can use custom widgets like the row and align the items by yourself (like start, center etc.). I would like to have more freedom for customizations. 
 
In my case I just can't center the legend and get evenly paddings because I have words with different length. I played a lot with the legend and legendItemBuilder properties but I could not find a working solution. 
<img width="336" alt="fd3876b7119c0381ccc111de63c663d3" src="https://user-images.githubusercontent.com/12775942/82029407-416b4a80-9697-11ea-9dff-b3891a479722.png">


I merged my code in your example if you want to look at it. 
[main.dart.zip](https://github.com/syncfusion/flutter-examples/files/4633050/main.dart.zip)
