### ISSUE TITLE
How to get charts data on json to backend in flutter 

### ISSUE THREAD

**Issue by ramsubramani** [syncfusion/flutter-examples#128]
hi 
    how to use dynamic charts data on the api format

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ramsubramani ,

Thanks for your interest in Suncfusion Flutter charts. We have analyzed your scenario and we have created a simple sample and attached below in which we have parsed JSON data to list and binded the list to chart data. The parsing of raw JSON data to dart object model is called deserialization.

We have 3 steps to convert/parse JSON into Dart Object (deserialization),
- get JSON object from string using jsonDecode() function
- create a class that has fields corresponding to key/value pairs of the JSON
- assign each JSON object value to the fields of the class instance (we will do this in factory .fromJson() method).

For example, if our JSON data for the chart which is available in the .json file say data.json,
```
[
        {
            "year": "Jan",
            "sales": 35.0
        },
        {
            "year": "Feb",
            "sales": 28.0
        },
        {
            "year": "Mar",
            "sales": 34.0
        },
        {
            "year": "Apr",
            "sales": 32.0
        },
]
```
then, it can be deserialized using the following way,
```
List<SalesData> chartData = [];

Future<String> _loadSalesDataAsset() async {
    return await rootBundle.loadString('assets/data.json');
  }

Future loadSalesData() async {
    String jsonString = await _loadSalesDataAsset();
    final jsonResponse = json.decode(jsonString);
    print(jsonResponse);
    setState(() {
      for(Map i in jsonResponse) {
        chartData.add(SalesData.fromJson(i));
      }
    });
  }
```
Also, create a SalesData class which contains the sales data for the chart. Include a fromJson() factory method to make it easy to create a SalesData object.
```
class SalesData {
  SalesData(this.year, this.sales);

  final String year;
  final double sales;

  factory SalesData.fromJson(Map<String, dynamic> parsedJson) {
    return SalesData(
      parsedJson['year'].toString(),
      parsedJson['sales'] as double,
    );
  }
}
```
Call the **loadSalesData()** method from the **initState()** as follows and set the **chartData** to the  charts's **datasource**. 
```
@override
  void initState() {
    super.initState();
    loadSalesData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter chart'),
        ),
        body: SfCartesianChart(
           // your configurations
            series: <ChartSeries<SalesData, String>>[
              LineSeries<SalesData, String>(
                  dataSource: chartData, // binded the deserialized JSON data to the chart's datasource
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
            ]
          )
      );
  }
```
The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4669397/sample.zip)

For further reference Parsing JSON object in Flutter, click [here](https://flutter.dev/docs/development/data-and-backend/json).

As we are not aware of the exact requirement you are requesting in this query "how to use dynamic charts data on the API format", kindly revert us with more information on the query so that it will be helpful in providing the solution sooner.

Regards,
Sriram Kiran.

**Comment by ramsubramani** [comment]
hi @JayavigneshwaranG 
Thank you so much ....how to set  y axis fixed number
