### ISSUE TITLE
[Question] how can i setup baseline on line/spline/barchart?

### ISSUE THREAD

**Issue by codenamics** [syncfusion/flutter-examples#131]
Hello,

It is possible to setup baseline on line/spline/bar chart?

thanks

**Comment by SriramKiranSenthilkumar** [comment]
Hi @codenamics ,

Thanks for your interest in Syncfusion Flutter chart widget. We have analyzed your scenario and we are not aware of the exact requirement of yours. So, we suspect that you are in need of either PlotBand or Axis Crossing feature available in that chart.

**PlotBand :**
Plot bands are also known as strip lines, which are used to shade the different ranges in plot area with different colours to improve the readability of the chart. We have created a simple sample in which we have rendered plot band in the chart by providing the necessary start and end values. Please refer the code snippet below for reference.
```
SfCartesianChart(
                        primaryXAxis:DateTimeAxis(
                            plotBands: <PlotBand>[
                              PlotBand(
                                 isVisible: true,
                                 start: 2001.5,
                                 end: 2002.5,
                                associatedAxisStart: 35,
                                associatedAxisEnd: 35.1,
                                color: Colors.black,
                            )   
                        )                    
                        // your configurations.
)
```
**Screenshot**
![image](https://user-images.githubusercontent.com/63577117/83027046-3fb56580-a04d-11ea-9767-aa0090a785cb.png)
The sample for reference can be found below,
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4689090/sample.zip)

**AxisCrossing :**
Axis crossing refers to the positioning of axis anywhere in the plot area using the crossesAt property of an axis. We have created a simple sample in which we have positioned the y-axis in the middle of the plot area using the crossesAt property of the axis. Please refer the code snippet below for reference.
```
SfCartesianChart(
            primaryYAxis: NumericAxis(
              crossesAt: 2002
            ),
            // your configurations.
)
```
**Screenshot**
![image](https://user-images.githubusercontent.com/63577117/83027317-9cb11b80-a04d-11ea-8964-957f3d20c8c9.png)
The sample for reference can be found below,
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4689109/sample.zip)

Please find the user guides for the plot band and axis crossing below,
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#plot-bands
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#axis-crossing
 
If your query is misunderstood at our end,  we request you to provide more information on your scenario in detail with example screenshots so that it will be helpful in providing the solution sooner.

Regards,
Sriram Kiran.

**Comment by codenamics** [comment]
Can I ask if you support box and whisker charts?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @codenamics ,

As of now, we do not have support for box and whisker chart in our chart widget package. We have already considered this as a feature request and created feedback for the same. It will be included in any one of our upcoming releases yet to come. You can track the status of the feature below.

https://www.syncfusion.com/feedback/13379

Regards,
Sriram Kiran.
