### ISSUE TITLE
LineSeries not displayed when combined with BarSeries

### ISSUE THREAD

**Issue by hnnngwdlch** [syncfusion/flutter-examples#133]
Hi,

when I try to combine line series and bar series in one chart, the line series is not displayed in the chart. This works, however, for all other combinations I tested (replace, for example, BarSeries with column series and it will work).

```
class _TestGraphState extends State<TestGraph> {
  @override
  Widget build(BuildContext context) {
    final List<DisplayedData> barSeriesData = [
      DisplayedData('20000000', 10000, Colors.yellow),
      DisplayedData('30000000', 15000, Colors.yellow),
      DisplayedData('40000000', 20000, Colors.yellow),
      DisplayedData('45000000', 25000, Colors.yellow),
      DisplayedData('50000000', 30000, Colors.yellow)
    ];
    final List<DisplayedData> lineSeriesData = [
      DisplayedData('20000000', 20000, Colors.black),
      DisplayedData('30000000', 20000, Colors.black),
      DisplayedData('40000000', 20000, Colors.black),
      DisplayedData('45000000', 20000, Colors.black),
      DisplayedData('50000000', 20000, Colors.black)
    ];
    return Scaffold(
      body: Center(
        child: Container(
          child: SfCartesianChart(
            primaryXAxis: CategoryAxis(),
            primaryYAxis: NumericAxis(),
            series: <ChartSeries>[
              BarSeries<DisplayedData, Object>(
                dataSource: barSeriesData,
                xValueMapper: (DisplayedData data, _) => data.xValueMapper,
                yValueMapper: (DisplayedData data, _) => data.yValueMapper,
                pointColorMapper: (DisplayedData data, _) => data.color,
              ),
              LineSeries<DisplayedData, Object>(
                dataSource: lineSeriesData,
                xValueMapper: (DisplayedData data, _) => data.xValueMapper,
                yValueMapper: (DisplayedData data, _) => data.yValueMapper,
                pointColorMapper: (DisplayedData data, _) => data.color,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DisplayedData {
  final Object xValueMapper;
  final num yValueMapper;
  final Color color;

  DisplayedData(
    this.xValueMapper,
    this.yValueMapper,
    this.color,
  );
}
```

**Comment by Arunsanthoshh** [comment]
Hi @hnnngwdlch ,

We have validated your query. We wish to let you know that in flutter charts, the bar chart could not be combined with any other chart types. The bar chart uses the vertical axis as x and horizontal axis as y, but other chart types use the vertical axis as y and horizontal axis as x. Due to this reason, you could not be able to combine the bar with other chart types. This is the actual behavior.

But you have mentioned that bar series with column series is working. But on our side, it is also not working. So, could you please share the example code snippet with the output of the bar with column series, which will be helpful for us to understand more about your scenario.

Thanks,
Arun

**Comment by hnnngwdlch** [comment]
Hi Arun, 

ok, understood, thank you!

I think my initial formulation was just misleading. What I wanted to describe is that I was able to display ColumnSeries + another series but not BarSeries + another series.  That, however, makes sense given your explanation.

I will close this issue.
