### ISSUE TITLE
Weird annotation placing based on index if CategoryAxis contains numbers

### ISSUE THREAD

**Issue by hnnngwdlch** [syncfusion/flutter-examples#134]
Hi,

if one uses numbers as values for the CategoryAxis and tries to display an annotation at a certain point (here: '300', 20000), the passed string value is treated as an index and the annotation is not displayed on the chart or at an unexpected position (in this case there is no index 300 since we only have 5 items). I would have to pass '2', 20000 so that the annotation is placed as expected. I wonder if this behavior is intended?

```
class _TestGraphState extends State<TestGraph> {
  @override
  Widget build(BuildContext context) {
    final List<DisplayedData> columnSeriesData = [
      DisplayedData('100', 10000, Colors.yellow),
      DisplayedData('200', 15000, Colors.yellow),
      DisplayedData('300', 20000, Colors.yellow),
      DisplayedData('400', 25000, Colors.yellow),
      DisplayedData('500', 30000, Colors.yellow)
    ];
    return Scaffold(
      body: Center(
        child: Container(
          child: SfCartesianChart(
            primaryXAxis: CategoryAxis(),
            primaryYAxis: NumericAxis(),
            series: <ChartSeries>[
              ColumnSeries<DisplayedData, String>(
                dataSource: columnSeriesData,
                xValueMapper: (DisplayedData data, _) => data.xValueMapper,
                yValueMapper: (DisplayedData data, _) => data.yValueMapper,
                pointColorMapper: (DisplayedData data, _) => data.color,
              ),
            ],
            annotations: [
              CartesianChartAnnotation(
                widget: Container(
                  padding: EdgeInsets.symmetric(
                    horizontal: 5,
                    vertical: 1,
                  ),
                  child: Text(
                    'myAnnotation',
                    style: TextStyle(
                      color: Colors.white,
                    ),
                  ),
                  decoration: BoxDecoration(
                    color: Colors.black,
                    borderRadius: BorderRadius.all(
                      Radius.circular(
                        15,
                      ),
                    ),
                  ),
                ),
                coordinateUnit: CoordinateUnit.point,
                x: '300',
                y: 20000,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DisplayedData {
  final String xValueMapper;
  final num yValueMapper;
  final Color color;

  DisplayedData(
    this.xValueMapper,
    this.yValueMapper,
    this.color,
  );
}
```

**Comment by Arunsanthoshh** [comment]
Hi @hnnngwdlch ,

We have analyzed your query and we wish to let you know that, this is the actual behavior of the annotation for the category axis. Because we can specify any value in a string (might be number or string), so we should not give the same value(in datasource) to x in annotation, it will work only in a numeric axis. When it comes to the category axis we should set the index of datasource to x value in the annotation. The index starts at 0.

Please find the below code snippet and outputs for both the numeric axis and category axis on annotation.

**Numeric axis and its annotation –**
`class _ChartSeriesTestbedSampleState extends State<ChartSeriesTestBed> {
  @override
  Widget build(BuildContext context) {

    final List<SalesData> chartData = [
      SalesData(1, 1),
      SalesData(2, 2),
      SalesData(3, 3),
    ];

    return Scaffold(
        body: Center(
            child: Container(
                child: SfCartesianChart(
      legend: Legend(isVisible: true),
      enableSideBySideSeriesPlacement: true,
      series: <ChartSeries>[
        ColumnSeries<SalesData, int>(
          dataSource: chartData,
          xValueMapper: (SalesData sales1, _) => sales1.sales,
          yValueMapper: (SalesData sales1, _) => sales1.sales1,
        )
      ],
      annotations: [
        CartesianChartAnnotation(
            widget: Container(
              child: Text(
                'myAnnotation',
                style: TextStyle(
                  color: Colors.white,
                ),
              ),
              decoration: BoxDecoration(
                color: Colors.black,
                borderRadius: BorderRadius.all(
                  Radius.circular(
                    15,
                  ),
                ),
              ),
            ),
            coordinateUnit: CoordinateUnit.point,
            x: 2,
            y: 2),
      ],
    ))));
  }
}

class SalesData {
  SalesData(this.sales, this.sales1);
  final int sales;
  final int sales1;
}

`
**Output --** 
![image](https://user-images.githubusercontent.com/53538082/84039346-bee85900-a9be-11ea-9ea9-7edb82e69bfa.png)

**Category axis and its annotation –**
 `class _ChartSeriesTestbedSampleState extends State<ChartSeriesTestBed> {
  @override
  Widget build(BuildContext context) {

    final List<SalesData> chartData = [
      SalesData(1, 1),
      SalesData(2, 2),
      SalesData(3, 3),
    ];

    return Scaffold(
        body: Center(
            child: Container(
                child: SfCartesianChart(
      **primaryXAxis: CategoryAxis(),**
      legend: Legend(isVisible: true),
      enableSideBySideSeriesPlacement: true,
      series: <ChartSeries>[
        ColumnSeries<SalesData, int>(
          dataSource: chartData,
          xValueMapper: (SalesData sales1, _) => sales1.sales,
          yValueMapper: (SalesData sales1, _) => sales1.sales1,
        )
      ],
      annotations: [
        CartesianChartAnnotation(
            widget: Container(
              child: Text(
                'myAnnotation',
                style: TextStyle(
                  color: Colors.white,
                ),
              ),
              decoration: BoxDecoration(
                color: Colors.black,
                borderRadius: BorderRadius.all(
                  Radius.circular(
                    15,
                  ),
                ),
              ),
            ),
            coordinateUnit: CoordinateUnit.point,
            x: 2,
            y: 2),
      ],
    ))));
  }
}

class SalesData {
  SalesData(this.sales, this.sales1);
  final int sales;
  final int sales1;
}
`
**Output --**
 
![image](https://user-images.githubusercontent.com/53538082/84039536-fe16aa00-a9be-11ea-8c53-c3a5e277c600.png)

Thanks,
Arun

**Comment by hnnngwdlch** [comment]
Hi Arun,

ok, thank you for the information!
