### ISSUE TITLE
Infinite scroll feature

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#145]
Hi,
is there any way to make an infinite scroll on a paginated endpoint?

I tried to make a request when a user pan the graph and has reached the end of the graph, but new data has added in the visible area of the graph, so it is already at the end of the graph and new request is send. and so on and on.

These are gif to better understand the problem

![Bad-impl](https://user-images.githubusercontent.com/5927329/85870204-0b100780-b7cd-11ea-94fc-2ecb40b96c80.gif)

![Bad-impl-2](https://user-images.githubusercontent.com/5927329/85870814-dcdef780-b7cd-11ea-9bcb-d2d08800a321.gif)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,
 
Greetings from Syncfusion. We have analyzed your scenario and currently, there is no support for infinite scroll feature in our chart library. However, we have already logged a feature request regarding the requested scenario and this feature will be included in Vol 3 main release 2020 which is expected to be rolled out at the end of September 2020. We will update you once the release is rolled out and we appreciate your patience until then.

You can also track the status of the feature request using the below link,
https://www.syncfusion.com/feedback/11947
 
Regards,
Sriram Kiran

**Comment by andrea689** [comment]
it's good, thank you!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

We are sorry that we were not able to include the requested feature regarding providing lazy loading support for cartesian charts due to some internal complexity as there are several cases to be ensured. So, we have planned and scheduled to include the requested feature for our vol 4 main release which is expected to be rolled out by the end of December 2020. Sorry for the inconvenience. We will update you once the release is rolled out and we appreciate your patience until then. You can also track the status of the feature using the below feedback link.
https://www.syncfusion.com/feedback/11947

Regards,
Sriram Kiran
