### ISSUE TITLE
onSelectionChanged not working properly when chart data has null values

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#152]
Hi,
when I use chart data with a null value and select a chart data after this value, the index returned from onSelectionChanged is the previous index (right index - 1).

<img width="264" alt="Screenshot 2020-06-29 at 18 06 30" src="https://user-images.githubusercontent.com/5927329/86032580-dc499980-ba37-11ea-824a-f40a9a9ea104.png">

In the example above, if I tap column on "14 Jun" the `onSelectionChanged` returns the right index (3), but if I tap column on "16 Jun" the `onSelectionChanged` returns the index of null value (4) instead of the right index (5)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,
 
Greetings from Syncfusion. We have analyzed your scenario and we would wish to explain to you in detail on how the series data points are stored when there is a null or empty point in the data source. For internal calculation and rendering purposes, we will maintain a separate data points list in the chart source and when there is a null point in the datasource then that point will be neglected from this list. Due to this only the index of the data points after the null data point differs. Currently, this is the default behaviour.

And, we would like to let you know about the empty point settings available in the series which can be used in these purposes. By using **emptyPointSettings** property in series, you can decide the action taken for empty points. There are four types of empty point modes available such as **drop**, **gap**, **zero** and **average**. 
•	When the empty point mode is set to **gap** or **drop**, the data point will not be rendered at the null data point’s position.
•	When the empty point mode is set to **zero**, a data point with y-value as 0 will be rendered at the null data point’s position.
•	When the empty point mode is set to **average**, a data point will be rendered at the null data point’s position with y-value calculated by taking the average of the previous and next data point’s y-values.

For further reference on the emptyPointSettings property, please check the user guide below,
https://help.syncfusion.com/flutter/cartesian-charts/series-customization#empty-points
 
Regards,
Sriram Kiran

**Comment by andrea689** [comment]
resolved, thank you!
