### ISSUE TITLE
Vertical auto zoom based only on visible data

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#156]
Hi,
is there a way to vertical auto zoom the chart based on the visible data?

Now I have this chart:

<img width="346" alt="Screenshot 2020-07-03 at 09 45 05" src="https://user-images.githubusercontent.com/5927329/86445119-2077bb00-bd12-11ea-9c0f-be2a2b1eb220.png">

I want that the chart use all the height, now it not use all' space because in the chart outside the visible area there is a peak:

<img width="346" alt="Screenshot 2020-07-03 at 09 45 16" src="https://user-images.githubusercontent.com/5927329/86445123-21a8e800-bd12-11ea-8edc-43f4abf25036.png">

I would like that the chart is auto zoomed when user pan the graph based on current visible data. Is there a way?

Thank you!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Greetings from Syncfusion. We have analyzed your scenario and we wish to let you know that we have already implemented the reported feature regarding the y-axis range changes dynamically according to the visible data points and this feature will be included in our Vol 2 main release which is expected to be rolled out by the mid of this week. We will update you once the release is rolled out and we appreciate your patience until then.

Thanks,
Sriram Kiran

**Comment by andrea689** [comment]
Perfect! Thank you!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Thanks for your patience. The reported feature regarding the y-axis range changes dynamically according to the visible data points when the chart is panned or zoomed is implemented and rolled out in our Vol 2 Main release. To achieve this feature, kindly upgrade the chart widget to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.44

Please get in touch with us if you require further assistance.

Thanks,
Sriram Kiran

**Comment by andrea689** [comment]
Hi @JayavigneshwaranG ,
 this feature does not work with latest release..

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

We have analyzed your scenario and we have created a simple sample to test the reported scenario with our latest chart widget package version. Unfortunately, the reported feature was working properly at our end.  To ensure this, we have also attached a video of this which can be found below.

Video link: [video.zip](https://github.com/syncfusion/flutter-examples/files/4932629/video.zip)

The sample used for testing can be found below
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4932633/sample.zip)


Since the reported scenario is not replicated at our end, kindly revert us with the below details. This will be helpful in further analysis and provide you with the solutions sooner. 

- Try to replicate the reported issue with the above sample 

- Or kindly share us the code snippet with your data source which you have used to render chart widget 


Regards,
Sriram Kiran.

**Comment by andrea689** [comment]
Hi @SriramKiranSenthilkumar,
I have replicated the issue with your sample, using `CategoryAxis` instead of `DateTimeAxis`, and removing `visibleMaximum` from `NumericAxis`:

```dart
              primaryXAxis: CategoryAxis(
                visibleMinimum: 20,
                visibleMaximum: 26,
              ),
              primaryYAxis: NumericAxis(
                //visibleMaximum: 4500,
                isVisible: false,
              ),
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Thanks for the revert. We have analyzed your scenario with the provided code snippet and we are able to replicate the reported issue at our end. We will consider this as a bug and will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then. 

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Thanks for your patience. The reported issue regarding the y-axis range changes dynamically according to the visible data points when the chart is panned or zoomed with category axis is fixed and rolled out in our weekly patch release. To overcome the reported issue, Kindly upgrade the chart widget package to the latest version below,
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.47

Regards,
Sriram Kiran

**Comment by andrea689** [comment]
Thank you, now it is working!
