### ISSUE TITLE
What version of syncfusion should I use, because my Flutter SDk version is 1.9.1+hotfix 6

### ISSUE THREAD

**Issue by coderJW** [syncfusion/flutter-examples#161]
<img width="2188" alt="WeChat13238618ee5909957059147fb4b22636" src="https://user-images.githubusercontent.com/15873406/86584070-f09d1180-bfb6-11ea-8840-9136e37f4638.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @coderJW ,

Thanks for using our Synfusion Flutter charts. We have analyzed your scenario and we found that you are using outdated flutter SDK version(flutter 1.9.1+hotfix 6) and due to this only, you are getting the reported compilation errors. So, we request you to kindly upgrade your Flutter SDK version to the latest stable channel version from the link below.
https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.5-stable.zip

Kindly revert us if you still face any problems after upgrading the Flutter SDK version.

Regards,
Sriram Kiran.
