### ISSUE TITLE
DataLabelSettings builder problems

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#187]
Hi,
I have three problems with use of DataLabelSettings builder:

```dart
DataLabelSettings(
  builder: (data, point, series, pointIndex, seriesIndex) {
    ...
  }
)
```

1. `data` value is not correct when use `visibleMinimum` and `visibleMaximum` 
2. When the column is too hight the label not appear, maybe because it doesn't calculate the space for the label well.
3. When move the chart, the label disappear and when stop move it reappear. It's annoying and without `builder` it doesn't happen.

<details>
  <summary>This is a code example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  return runApp(ChartApp());
}

class ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Chart Demo',
      theme: ThemeData(primarySwatch: Colors.blue, brightness: Brightness.dark),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  // ignore: prefer_const_constructors_in_immutables
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter chart'),
        ),
        body: Container(
          height: 300,
          child: SfCartesianChart(
              primaryXAxis: CategoryAxis(
                visibleMinimum: 17,
                visibleMaximum: 23,
              ),
              primaryYAxis: NumericAxis(),
              zoomPanBehavior: ZoomPanBehavior(
                enablePinching: true,
                enablePanning: true,
                zoomMode: ZoomMode.x,
              ),
              series: <ChartSeries<SalesData, DateTime>>[
                ColumnSeries<SalesData, DateTime>(
                  dataSource: <SalesData>[
                    SalesData(DateTime(2019, 6, 10), 3000),
                    SalesData(DateTime(2019, 6, 11), 800),
                    SalesData(DateTime(2019, 6, 12), 300),
                    SalesData(DateTime(2019, 6, 13), 500),
                    SalesData(DateTime(2019, 6, 14), 500),
                    SalesData(DateTime(2019, 6, 15), 400),
                    SalesData(DateTime(2019, 6, 16), 800),
                    SalesData(DateTime(2019, 6, 17), 200),
                    SalesData(DateTime(2019, 6, 18), 800),
                    SalesData(DateTime(2019, 6, 19), 500),
                    SalesData(DateTime(2019, 6, 20), 300),
                    SalesData(DateTime(2019, 6, 21), 1200),
                    SalesData(DateTime(2019, 6, 22), 200),
                    SalesData(DateTime(2019, 6, 23), 500),
                    SalesData(DateTime(2019, 6, 24), 800),
                    SalesData(DateTime(2019, 6, 25), 700),
                    SalesData(DateTime(2019, 6, 26), 0),
                    SalesData(DateTime(2019, 6, 27), 100),
                    SalesData(DateTime(2019, 6, 28), 600),
                    SalesData(DateTime(2019, 6, 29), 3500),
                    SalesData(DateTime(2019, 6, 30), 700),
                    SalesData(DateTime(2019, 7, 1), 500),
                    SalesData(DateTime(2019, 7, 2), 300),
                    SalesData(DateTime(2019, 7, 3), 800),
                    SalesData(DateTime(2019, 7, 4), 300),
                    SalesData(DateTime(2019, 7, 5), 200),
                    SalesData(DateTime(2019, 7, 6), 500),
                    SalesData(DateTime(2019, 7, 7), 900),
                    SalesData(DateTime(2019, 7, 8), 200),
                    SalesData(DateTime(2019, 7, 9), 400),
                    SalesData(DateTime(2019, 7, 10), 100),
                    SalesData(DateTime(2019, 7, 11), 800),
                    SalesData(DateTime(2019, 7, 12), 600),
                    SalesData(DateTime(2019, 7, 13), 3200),
                    SalesData(DateTime(2019, 7, 14), 1000),
                    SalesData(DateTime(2019, 7, 15), 800),
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  dataLabelSettings: DataLabelSettings(
                    isVisible: true,
                    builder: (data, point, series, pointIndex, seriesIndex) {
                      final datum = data as SalesData;
                      return Container(
                        height: 36,
                        child: Column(
                          children: [
                            Icon(Icons.note, size: 18),
                            Text(datum.sales.toString()),
                          ],
                        ),
                      );
                    },
                  ),
                )
              ]),
        ));
  }
}

class SalesData {
  SalesData(this.year, this.sales);

  final DateTime year;
  final double sales;
}

```

</details>

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-18 at 15 42 30](https://user-images.githubusercontent.com/5927329/90520310-76d97580-e169-11ea-808c-80eb892e9490.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Greetings from Syncfusion. We have analyzed your scenarios and provided the response for your queries below.

**Query-1: (Data value is not correct when use visibleMinimum and visibleMaximum)**

We have analyzed on this query and we are able to replicate the reported issue regarding the data value are not correct when using visible minimum and visible maximum for the axis. We will consider this as a bug, and we will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

**Query-2: (When the column is too height the label does not appear, maybe because it doesn't calculate the space for the label well.)**

We have analyzed on this query and we have already working on improving the rendering of the data label template/builder for displaying the custom data labels that are getting hidden when the data points are close to the edges of the chart. We have also tested your scenario with our improved source at our end and the data label builder which are getting hidden for the data points at the edges of the chart are getting rendered properly similar to the rendering of the normal data label available in the chart. We have also taken screenshots of the rendering of the data label builder in the chart with the improved source at our end and attached below for your reference.
![image](https://user-images.githubusercontent.com/63577117/90656845-1b3de380-e260-11ea-9795-62592a772fcf.png)

We will include this improvement in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.


**Query-3: (When move the chart, the label disappear and when stop move it reappear. It's annoying and without builder it doesn't happen.)**

We have analyzed on this scenario and we are able to replicate the reported issue regarding the data label getting disappeared when panning the chart and reappear when the panning is stopped. This is already a known issue and we are already analyzing on this issue at our end and we will include the fix for the reported issue in our Vol 3 Main Release which is expected to be rolled out by the end of next month (September 2020). We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by andrea689** [comment]
Thank you so much, always super helpful!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Thanks for your patience. The reported issues regarding the data value are not correct in the data label builder when using visible minimum and visible maximum for the axis (Query-1) and also the improvement regarding the rendering of the data label template/builder for displaying the custom data labels that are getting hidden when the data points are close to the edges of the chart (Query-2) are now fixed and rolled out in our weekly patch release. To overcome the reported issue kindly upgrade the chart widget package version to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.55

Regards,
Sriram Kiran

**Comment by andrea689** [comment]
Hi @SriramKiranSenthilkumar,
I tested new 18.2.56 version and I have find new bug.. when I use `labelAlignment: ChartDataLabelAlignment.outer`, sometime the label is not placed correctly.

<img width="340" alt="Screenshot 2020-09-02 at 10 49 34" src="https://user-images.githubusercontent.com/5927329/91960511-41f12500-ed0a-11ea-8911-352c341aec4c.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

We have analyzed your scenario and we would like to share some information regarding the customer data label rendering behaviour when they are close to the edges of the chart area. For example, in your screenshot, the custom data label at the '25 Aug'  x-value is slightly moved downwards because as there is no space for that data label to render outside of the point and so it is moved downwards rendered. This is the default behaviour of the data label when they are at the edges of the chart area and with **labelAlignment** property set to **outer** value. if you don't want the data label builder to be rendered in this way, you set the **labelAlignment** property to **auto** which will render the data label inside and outside of the data point according to the rendering space available for the data label.

Regards,
Sriram Kiran
