### ISSUE TITLE
[bug] Interactive Gauge drag not working

### ISSUE THREAD

**Issue by robertsLando** [syncfusion/flutter-examples#188]
I have created an interactive gauge using the code below: 

```dart
SfRadialGauge(
                  title: settings.title != null ? GaugeTitle(text: '${settings.title}', borderWidth: 2) : null,
                  axes: <RadialAxis>[
                  RadialAxis(
                      axisLineStyle: AxisLineStyle(
                          cornerStyle: settings.donut ? CornerStyle.bothFlat : CornerStyle.bothCurve,
                          thickness: 0.2,
                          thicknessUnit: GaugeSizeUnit.factor),
                      showTicks: false,
                      showLabels: true,
                      startAngle: settings.donut ? 90 : 130,
                      endAngle: settings.donut ? 90 : 50,
                      minimum: settings.min,
                      maximum: settings.max,
                      onAxisTapped: onValueChange,
                      //ranges: settings.ranges.map((e) => GaugeRange(startValue: e.start, endValue: e.stop, color: HexColor.fromHex(e.color))).toList(),
                      pointers: <GaugePointer>[
                        RangePointer(
                            cornerStyle: CornerStyle.bothCurve,
                            value: value,
                            color: HexColor.fromHex(settings.ranges
                                .firstWhere(
                                    (r) => value >= r.start && value <= r.stop)
                                .color),
                            onValueChangeEnd: onValueChange,
                            onValueChanging: onPointerValueChanging,
                            enableDragging: settings.interactive,
                            enableAnimation: true,
                            animationDuration: 0.5,
                            width: 0.2,
                            sizeUnit: GaugeSizeUnit.factor),
                        MarkerPointer(
                          value: value - (settings.max - settings.min) * 0.02,
                          color: Colors.white,
                          markerHeight: 10.0,
                          markerWidth: 10.0,
                          enableAnimation: true,
                          animationDuration: 0.5,
                          markerType: MarkerType.circle,
                        ),
                      ],
                      annotations: <GaugeAnnotation>[
                        GaugeAnnotation(
                            widget: Column(
                              mainAxisSize: MainAxisSize.min,
                              children: <Widget>[
                                Text(
                                  '${value.toStringAsFixed(settings.decimals)} ${settings.units}',
                                  style: TextStyle(
                                    fontSize: 20,
                                    fontWeight: FontWeight.bold,
                                  ),
                                )
                              ],
                            ),
                            positionFactor: 0.13,
                            angle: 0)
                      ])
                ]);
```

It is placed in a card inside a scrollable grid, when I try to drag the pointer it doesn't work and it scrolls instead of dragging

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertsLando ,

We have analyzed your scenario with the provided widget tree case and we are able to replicate the reported issue at our end. As the reported issue is due to some internal problems in the Flutter framework, we will be considering your case also for the analysis in order to provide a fix for the reported issue in our chart source and we will include the fix for the reported issue in our Vol 3 Main release which is expected to be rolled by the end of next month (September 2020). We will update you once the release is rolled out and we appreciate your patience until then.

Also to mention that we will consider your case also in the same [feedback ](https://www.syncfusion.com/feedback/14635)which we have mentioned previously.


Regards,
Sriram Kiran

**Comment by robertsLando** [comment]
Additional context: Also seems impossbile to set gauge value to the min value, it stucks to around 10%, also max value is really difficult to set as it usually stops to 99.9%

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertsLando,

We have analyzed your scenario and we are able to replicate the reported issue regarding the inability to set the gauge value to the available minimum value and maximum value. We will consider this as a bug and we will include the fix for the reported issue in our Vol 3 main release which is expected to be rolled out by the end of next month (September 2020). We will update once the release is rolled out and we appreciate your patience until then.

Also to mention that you can use the same [feedback](https://www.syncfusion.com/feedback/14635) which we have mentioned previously for tracking the reported bug too.

Regards,
Sriram Kiran

**Comment by robertsLando** [comment]
@SriramKiranSenthilkumar Based on my experience with oder draggable widgets I have been able to fix this problem by using `LongPress` handlers instead of `PanHandlers` for dragging events. 

If you are using a GestureControl to handle the gauges drags I suggest so to use 

```
onLongPressStart
onLongPressMoveUpdate
onLongPressEnd
```

instead of 

```
onPanStart
onPanUpdate
onPanEnd
```

And everything will work, also I think that using a long press to start dragging is more user friendly

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertsLando ,

Thanks for your suggestion. We will consider this too while providing fix for the reported drag related issue.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertsLando,

Thanks for your patience. We would like to share some information about the cause for the reported issue regarding the gauge pointer dragging does not work when the gauge is placed in this widget tree(CustomScrollView -> SliverToBoxAdapter -> MasonryGrid > Container > Card > RadialGauge widget)

On analyzing this issue for providing a fix, we found that in the masonry grid package, they add every widget which you have added in the Masonry grid in the following manner like below.
```
Row( children: [
  Expanded(
   child: Column(
     key: GlobalKey(),
     children:[
       SfRadialGauge1(),
    ])
  ),
  Expanded(
    child: Column(
      key: GlobalKey(),
      children:[
        SfRadialGauge2(),
    ])
  )
]);
```
And in the above code snippet, you can see that they have added the global key for each and every widget in the collection and these global keys are only used for re-rendering the each and every widget when user interaction is done(i.e., scrolling down/Up in the grid) in the screen.

Due to the global key that is used in the third-party package(masonry grid) and in your code snippet, you have called the setState to set the gauge annotation value, on dragging the gauge, the whole gauge is re-rendering twice and so that only it is looking like the dragging is not performed properly.

So, we have found a way to resolve this issue in the sample level itself with the help of the **StateSetter** and **StatefulBuilder** for updating the gauge annotation text widget value whenever required without re-rendering the whole gauge widget every time when the annotation value is changed. Please refer the code snippet below for reference.
```
class _MyHomePageState extends State<MyHomePage> {
 StateSetter textStateSetter; // Initialized a state setter for the annotation text widget
@override
  Widget build(BuildContext context) {
    return Scaffold(
        body: CustomScrollView(
          primary: true,
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: MasonryGrid(
                column: 1,
                mainAxisSpacing: 2,
                children: <Widget>[
                  Card(
                    child: SfRadialGauge(
                      // Your configurations
                      annotations: <GaugeAnnotation>[
                        GaugeAnnotation(
                          widget: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: <Widget>[
                              StatefulBuilder( // Used statefulBuilder as parent for the annotation text widget.
                                builder: (BuildContext context, Function setState){
                                  textStateSetter = setState; // Setting textstateSetter for the annotation text widget
                                  return Text(
                                   '$_currentValue',
                                   style: const TextStyle(
                                     fontSize: 20,
                                     fontWeight: FontWeight.bold,
                                    ),
                                  );})
                                 ],
                               ),
                               positionFactor: 0.13,
                               angle: 0)
                              ])
                        ]),
                  ),
                ],
              ),
            )
          ],
        ));
  }
  void onPointerValueChanged(double value) {
    if (value.toInt() > 6) {
      textStateSetter(() { // setting the value for the annotation text value using state setter
        _currentValue = value.roundToDouble();
        final int _value = _currentValue.toInt();
        _markerValue = _currentValue - 2;
      });
    }
  }
}
```

In the above code snippet, we have used the StateSetter instead of the **setstate** for the annotation builder's text widget. Whenever you trigger the **setState** it renders the hole widget but while using the **StateSetter** it will be triggered only the specific widget that is inside the **StatefulBuilder** so it doesn’t Re-render the hole widget. We have also attached the modified sample below for reference.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5327076/sample.zip)

Please check with the above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran.

**Comment by robertsLando** [comment]
This actually doesn't fix my issue, as I said in my previous comment this issue is still present without the mansonry grid, it happens in general when the widget is placed inside a scroll container (also singlechildscrollview has the same issue). 

Additionally the problem with the [min/max value](https://github.com/syncfusion/flutter-examples/issues/188#issuecomment-679831224) isn't fixed in this way

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertsLando,

We have tried to reproduce interactive gauge drag issue with and without the masonry grid. But the dragging is working properly at our end, and we have also attached the simple sample with the fix which we used for testing. Please check the below attached sample and revert us if you still face any issue related to dragging and also if possible, kindly please try to reproduce the reported issue in a simple sample and share it with us so that it will be helpful providing the solutions sooner.

The sample used for testing can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5365659/testsample.zip)


Regards,
Sriram Kiran
