### ISSUE TITLE
build for desktop

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#190]
build for desktop mac error
pls fix

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi,

Greetings from Syncfusion. We have not provided desktop support for our Flutter widgets yet because the Flutter desktop support is not yet moved to the stable channel in the Flutter framework. Once the Flutter team moves this desktop support to the stable channel, we will make the necessary changes at our end.

As of now, we have provided support for mobile and web alone for our Flutter widgets.

Regards,
Sriram Kiran

**Comment by esDotDev** [comment]
The plugin architecture for all 3 desktop platforms has stabilized. Probably ok to try and add support now.
