### ISSUE TITLE
[Chart]Does it support dotted display?

### ISSUE THREAD

**Issue by NeverOvO** [syncfusion/flutter-examples#199]
Hello, I did not find the dotted line in the Demo. Does it support dotted line display, or what parameters do I need to configure?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @NeverOvO,

Greetings from Syncfusion. We have analyzed on your query and yes, we have provided support for rendering the line chart as the dotted or dashed line in our chart widget package. For achieving this, you can use the **dashArray** property of the Line series available in our chart in order to render the line chart in dotted or dashed line. Also, we have created and attached below a simple chart sample in which we have rendered a line chart in dotted or dashed format with the help of the **dashArray** property of the series. Please refer the code snippet below for reference.
```
SfCartesianChart(
            primaryXAxis: CategoryAxis(),
            series: <ChartSeries<SalesData, String>>[
              LineSeries<SalesData, String>(
                dashArray: <double>[3, 3],  // Provided dashArray values for the line chart
                dataSource: chartData,
                xValueMapper: (SalesData sales, _) => sales.year,
                yValueMapper: (SalesData sales, _) => sales.sales,
              )
            ]
)
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/63577117/92577726-9bc49280-f2a8-11ea-8f81-4c8575f461c1.png)

The sample for reference can be found below.
[dottedlinechart.zip.zip](https://github.com/syncfusion/flutter-examples/files/5193889/dottedlinechart.zip.zip)

For further reference on dashArray property, please check the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/chart-types#dashed-line

Please check the above-attached sample and revert us if you require further assistance on this.

Regards,
Sriram Kiran

**Comment by NeverOvO** [comment]
Thank you for your reply, it solved my problem perfectly.

**Comment by NeverOvO** [comment]
I'm sorry, the solution you provided before did solve my problem, but now my data volume has reached 300, but the broken line is a straight line, but the dotted line is not shown.
Screenshot：

<img width="278" alt="image" src="https://user-images.githubusercontent.com/34906510/92685950-4dc49300-f36b-11ea-9975-d02a8422b4c5.png">

Configuration：dashArray: <double>[0.4,2.4],

**Comment by SriramKiranSenthilkumar** [comment]
Hi @NeverOvO,

We have analyzed your scenario at our end and we would like to share some information regarding the behaviour of the rendering of the close chart data points in dashed line using dashArray available in the chart. If the chart data points are so close as the space between them are only say 5 pixels and also the provided dash array format is quite fewer values then there won't be available space to render the dashed path correctly for those close data points and so it renders the dashed line so close so that they are visible as a straight line but if you try zooming the chart you can be able to see that the dashed lines are rendered correctly but rendered so close as there is no available space between those points. This is the default behaviour of the dashed path available in the Flutter framework.

In order to overcome this rendering issue, you can use the **FastLineSeries** available in our chart widget instead of the **LineSeries** so that the dashed line gets rendered correctly. We have also ensured this by creating a simple chart sample similar to the provided screenshot and rendered the fast line series with lesser dash array format. We have attached the sample below for your reference. 
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5214176/sample.zip)

For further reference on **FastLineSeries**, please refer the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/chart-types#fast-line-chart

Please check the above attached sample and revert us if you require further assistance on this.

Regards,
Sriram Kiran

**Comment by NeverOvO** [comment]
Thank you very much for your prompt reply. With your help, I have solved all current problems. Thanks again for your help!
