### ISSUE TITLE
[CHART] zoom and move

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#201]
zoom is not good pls fix

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi,

Greetings from Syncfusion. We have analyzed on your query and as we are not sure of you exact scenario, we request you to share us with more information in detail about the zoom behaviour issues which you have encountered at your end and also if possible, revert us with the replication procedures for the encountered zoom related issues so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran
