### ISSUE TITLE
move chart to x,y

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#205]
please add function move to x,y posation 
moveChartToX
moveChartToXY

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi,

Greetings from Syncfusion. We have analyzed your query at our end and we are sorry that we are not exactly sure of your requirement or scenario which you have requested in your query. So, we kindly request you to share us with more information about your requirement or scenario in detail along with example screenshot or video if possible so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran
