### ISSUE TITLE
Zoom to chart

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#206]
please add custom Scale to Chart 
ScaleX
ScaleY
ScaleXY

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi,

Greetings from Syncfusion. We have analyzed your scenario at our end and we would like to share some information regarding the `zoomFactor ` and `zoomPosition` properties of an axis which can be used to scale the chart by providing values for them accordingly and these properties can be set to both x-axis and y-axis independently in the chart. Also, you can use the `visibleMinimum `and `visibleMaximum `properties of an axis which can be used to provide customer visible range for both the axis in order to view only the points in the provided range for the axes. For further reference on the **zoomFactor**, **zoomPosition**, **visibleMinimum** and **visibleMaximum** properties, please check the user guides below.

zoom factor: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/zoomFactor.html
zoom position: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/zoomPosition.html
visible minimum: https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-minimum
visible maximum: https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-maximum

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran
