### ISSUE TITLE
PDF | Invalid argument (The character is not supported by the font.): 26053

### ISSUE THREAD

**Issue by Daibaku9999** [syncfusion/flutter-examples#211]
I'm trying to generate PDF that has table.
But error says like so
`Invalid argument (The character is not supported by the font.): 26053`

How can I fix this?
Thank you for the great plugin!!

**Code**

```
final PdfDocument document = PdfDocument();
final PdfPage page = document.pages.add();
final PdfGrid grid = PdfGrid();
grid.columns.add(count: 7);
final PdfGridRow headerRow = grid.headers.add(1)[0];
headerRow.cells[0].value = '日付';
headerRow.cells[1].value = '出勤時刻';
headerRow.cells[2].value = '退勤時刻';
headerRow.cells[3].value = '休憩時間';
headerRow.cells[4].value = '労働時間';
headerRow.cells[5].value = '時間外労働';
headerRow.cells[6].value = '深夜残業';
headerRow.style.font = PdfStandardFont(PdfFontFamily.helvetica, 10, style: PdfFontStyle.bold);
final PdfGridRow row = grid.rows.add();
for (int i = 1; i < 31; i++) {
  row.cells[0].value = '$i日';
  row.cells[1].value = '8:31';
  row.cells[2].value = '18:00';
  row.cells[3].value = '1:00';
  row.cells[4].value = '8:28'; 
  row.cells[5].value = '0:28';
  row.cells[6].value = '0:00';
}
grid.style.cellPadding = PdfPaddings(left: 0, top: 0);
grid.draw(page: page, bounds: Rect.fromLTWH(0, 0, page.getClientSize().width, page.getClientSize().height));
final List<int> bytes = document.save();
document.dispose();
FileSaveHelper.saveAndLaunchFile(bytes, 'table.pdf');
```

**Comment by Anand3595** [comment]
Hi Daibaku9999,

Thanks for contacting Syncfusion support. The default font of PdfGrid is PdfStandardFont and it's not supports unicode and Chineese, Japaneese and Korean text. If the text in PdfGrid have CJK text, we can use the font for the grid as PdfCjkStandardFont instead of using PdfStandardFont as mentioned below code snippet.

> final PdfDocument document = PdfDocument();
final PdfPage page = document.pages.add();
final PdfGrid grid = PdfGrid();
grid.style.font = **PdfCjkStandardFont(PdfCjkFontFamily.monotypeHeiMedium, 10)**;
grid.columns.add(count: 7);
final PdfGridRow headerRow = grid.headers.add(1)[0];
headerRow.cells[0].value = '日付';
headerRow.cells[1].value = '出勤時刻';
headerRow.cells[2].value = '退勤時刻';
headerRow.cells[3].value = '休憩時間';
headerRow.cells[4].value = '労働時間';
headerRow.cells[5].value = '時間外労働';
headerRow.cells[6].value = '深夜残業';
headerRow.style.font = **PdfCjkStandardFont(PdfCjkFontFamily.monotypeHeiMedium, 10, style: PdfFontStyle.bold)**;
final PdfGridRow row = grid.rows.add();
for (int i = 1; i < 31; i++) {
  row.cells[0].value = '$i日';
  row.cells[1].value = '8:31';
  row.cells[2].value = '18:00';
  row.cells[3].value = '1:00';
  row.cells[4].value = '8:28';
  row.cells[5].value = '0:28';
  row.cells[6].value = '0:00';
}
grid.style.cellPadding = PdfPaddings(left: 0, top: 0);
grid.draw(page: page, bounds: Rect.fromLTWH(0, 0, page.getClientSize().width, page.getClientSize().height));
final List<int> bytes = document.save();
document.dispose();

Note: We can able to apply the specific font to the specific cell in PdfGrid by using **PdfGrid.rows[rowIndex].cells[columnIndex].style.font** property. 
 
With Regards,
Anand P

**Comment by Daibaku9999** [comment]
It did work, thanks a lot!!
