### ISSUE TITLE
Add animation on data source changed for SplineAreaSeries

### ISSUE THREAD

**Issue by jstnw10** [syncfusion/flutter-examples#215]
Hey,

It would be nice if you could add animations to SplineAreaSeries.  That's all.

Have a nice day y'all

**Comment by SriramKiranSenthilkumar** [comment]
Hi @jstnw10,

Greetings from Syncfusion. We have analyzed your scenario and we have already provided dynamic series animation support for our chart widget and to achieve this series animation feature while updating the series data points in the chart, you can use the **[`animationDuration`](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/animationDuration.html)** property of the series available in the chart. We have also attached a simple GitHub sample below in which we have dynamically updated the chart data points using a timer and on dynamic series data points updates, the chart series gets animated dynamically.
Sample link:
https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/area_series/animation_area_chart.dart

For further reference on animation features, please refer the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/series-customization#animation

Regards,
Sriram Kiran

**Comment by jstnw10** [comment]
Thanks for your answer.

It does not work with SplineArea.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @jstnw10,

The reported issue regarding the dynamic animation not working for spline area series is due to an internal bug in the chart source. We have analyzed on this at our end and provided a fix for the reported issue and included in our weekly patch release which released on 7th October 2020(Yesterday). To overcome the reported issue, kindly please upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.38

Please get in touch with us if you would require further assistance.

Regards,
Sriram Kiran
