### ISSUE TITLE
RenderFlex children have non-zero flex but incoming height constraints are unbounded.

### ISSUE THREAD

**Issue by patv2learn** [syncfusion/flutter-examples#223]
When trying to put Pie or Doughnut or Radial bar in column its not working at all and gives following error.

**RenderFlex children have non-zero flex but incoming height constraints are unbounded.**

Here is the sample code from example and just wrap it in Column.

```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

class SyncfusionChart extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final List<ChartData> chartData = [
      ChartData('David', 25),
      ChartData('Steve', 38),
      ChartData('Jack', 34),
      ChartData('Others', 52)
    ];

    return Scaffold(
      body: Center(
        child: Container(
          child: Column(
            children: [
              SfCircularChart(
                series: <CircularSeries>[
                  PieSeries<ChartData, String>(
                    dataSource: chartData,
                    pointColorMapper: (ChartData data, _) => data.color,
                    xValueMapper: (ChartData data, _) => data.x,
                    yValueMapper: (ChartData data, _) => data.y,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ChartData {
  ChartData(this.x, this.y, [this.color]);
  final String x;
  final double y;
  final Color color;
}

```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @patv2learn,

Greetings from Syncfusion. We have analyzed your scenario and we are able to replicate the reported issue at our end regarding the circular charts when wrapped inside a column widget, throws RenderFlex error exception and this issue is due to the circular charts does not have any default height constraints in the source. We will consider this as a bug, and we will include the fix for the reported issue in our weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @patv2learn,

Thanks for your patience. The reported issue regarding the circular charts when wrapped inside a column widget throws RenderFlex related error/exception is fixed and rolled out in our weekly patch release. To overcome the reported issue, kindly please upgrade the chart widget package to the latest version below.

https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.42

Regards,
Sriram Kiran
