### ISSUE TITLE
Rounded corners only on top of the column

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-examples#229]
It's possible to add a round corner only on top of the column? As seen in the image.
![imagem](https://user-images.githubusercontent.com/33434500/96498227-b2fd8500-1243-11eb-9877-5037ef3edc2b.png)

**Comment by LuisCampos97** [comment]
The code should be this, but it does not round the corners!

```dart
BarSeries<ChartData, String>(
                dataSource: [data()],
                borderRadius: BorderRadius.vertical(top: Radius.circular(30)), <----
                xValueMapper: (ChartData serie, _) => "Margin",
                yValueMapper: (ChartData serie, _) => serie.value)
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LuisCampos97,

Thanks for contacting Syncfusion Support. We have analyzed your scenario and we are able to replicate the reported issue regarding when setting border-radius to add rounded corners for specific corners of the column is not working properly. We will consider this as a bug and will include the fix for the reported issue in our upcoming weekly patch release which expected to be rolled by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Also, we found that this issue is only occurring when the animation is enabled for the chart series. So, we request you to set the `animationDuration `property of the chart series as `0`, in order to achieve the requested scenario regarding add rounded corner only on top of the column until the reported issue is fixed and rolled out. Please refer the code snippet below for further reference.
```
BarSeries<ChartData, String>(
                animationDuration: 0, // setting animation duration to 0 to disable rendering animation of the chart series.
                dataSource: [data()],
                // Setting border-radius to render that top of the column in rounder corner.
                borderRadius: BorderRadius.vertical(top: Radius.circular(30)), 
                xValueMapper: (ChartData serie, _) => "Margin",
                yValueMapper: (ChartData serie, _) => serie.value)
```

Regards,
Sriram Kiran

**Comment by LuisCampos97** [comment]
Many thanks for the reply!
It worked like that. I will then wait for the weekly update.

**Comment by Arunsanthoshh** [comment]
Hi @LuisCampos97,

We are glad to announce that our Flutter weekly patch release (v18.3.44) has been successfully rolled out and we have included the fix for the issue “Rounded corners only on the top of the column”. So, update your charts package to this version. You can download the updated charts package in the below link.
 
Updated package - https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.44 
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
 
Thanks,
Arun

**Comment by LuisCampos97** [comment]
Thank you very much @Arunsanthoshh !
