### ISSUE TITLE
[SfCartesianChart] Different colors in same bar in BarSeries

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-examples#235]
Hi!
Its possible to have different colors in same bar in BarSeries like the next image?

![image](https://user-images.githubusercontent.com/33434500/97573161-3efc7300-19e1-11eb-94ed-76fa2bbd7e35.png)

Thanks!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LuisCampos97,

Greetings from Syncfusion. We have analyzed your scenario at our end and we have created a simple workaround sample in which we have used two series to achieve your requirement. In the workaround sample, we have used two series types namely column and range column series and we have set the **`isTransposed`** property of the **`SfCartesianchart`** to true in order to render the column and range column series horizontally to look like a bar series. In the column series, we have set different colours for each column using the `pointColorMapper `property of the series and with the help of the range column series, we have provided the data source range values accordingly so that the second colour for the same bar data points can be rendered. Please refer the code snippet below for further reference.
```
SfCartesianChart( 
             // setting false to this property to render the series one above the other.
            enableSideBySideSeriesPlacement: false,
            // To change the orientation of the x-axis to vertical and y-axis to horizontal.
            isTransposed: true,
            primaryXAxis: CategoryAxis(opposedPosition: true),
            primaryYAxis: NumericAxis(
              isInversed: true,
            ),
            series: <ChartSeries<_SalesData, String>>[
              // First Column series to render the default chart with required color
              ColumnSeries<_SalesData, String>(
                  dataSource: <_SalesData>[
                    _SalesData('Jan', 10000, color: Colors.redAccent[400]),
                    _SalesData('Feb', 7000, color: Colors.orange),
                  ],
                  xValueMapper: (_SalesData sales, _) => sales.year,
                  yValueMapper: (_SalesData sales, _) => sales.sales,
                  pointColorMapper: (_SalesData sales, _) => sales.color),
               // range column series to render the second color for the first series by providing necessary range values for the series. 
              RangeColumnSeries<_SalesData, String>(
                dataSource: <_SalesData>[
                  _SalesData('Jan', 10000, high: 9900, low: 7500),
                  _SalesData('Feb', 7000, high: 6900, low: 4500),
                ],
                color: Colors.grey,
                xValueMapper: (_SalesData sales, _) => sales.year,
                highValueMapper: (_SalesData sales, _) => sales.high,
                lowValueMapper: (_SalesData sales, _) => sales.low,
              ),
            ]
)
```
**Screenshot:**
![Screenshot_20201030-195020](https://user-images.githubusercontent.com/63577117/97718065-7c4d2780-1aeb-11eb-9db0-44f690e9c5b5.jpg)

The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5465736/sample.zip)

Please check with the above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by LuisCampos97** [comment]
That's it!
Thank you very much!
