### ISSUE TITLE
How to draw reference lines, dotted lines

### ISSUE THREAD

**Issue by chongbo2013** [syncfusion/flutter-examples#240]
![image](https://user-images.githubusercontent.com/3191545/99764773-bb91f580-2b38-11eb-9bf9-a6c8f391f5dc.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @chongbo2013,

Greetings from Syncfusion. We have analyzed your scenario with the provided information at our end and we would like to share some information regarding the plot band feature available in our chart. Using the plot band feature, you can be able to plot lines in the chart on the required y-axis value or x-axis value respectively. We have created a simple chart sample in which we have rendered two line series and also rendered a plotline using the plot band feature to act as a reference line in the chart. Please refer the code snippet below for further reference.
```
SfCartesianChart(
            primaryXAxis: NumericAxis(),
            primaryYAxis: NumericAxis(
              labelFormat: '{value}%', 
              // Rendered a plot line using plotbands in y-axis.
              plotBands: [
               PlotBand(
                  isVisible: true,
                  // provided the same y-value to start and end property in order to render the plotline for that y-value.
                  start: 18,
                  end: 18,
                  borderWidth: 2,
                  borderColor: Colors.blueAccent,
                  // Label text for the reference plot line
                  text: 'Ref Line',
                  textStyle: TextStyle(color: Colors.blue),
                   // provided dash array to render the line in dashed format.
                  dashArray: <double>[5, 3])
              ]
             ),
            series: <ChartSeries<_ChartData, double>>[
              LineSeries<_ChartData, double>(
                  dataSource: chartData,
                  xValueMapper: (_ChartData data, _) => data.x,
                  yValueMapper: (_ChartData data, _) => data.y1,
                  markerSettings: MarkerSettings(isVisible: true)),
              LineSeries<_ChartData, double>(
                  dataSource: chartData,
                  xValueMapper: (_ChartData data, _) => data.x,
                  yValueMapper: (_ChartData data, _) => data.y2,
                  markerSettings: MarkerSettings(isVisible: true))
            ]
)
```
**Screenshot :**
![Screenshot_20201123-180643](https://user-images.githubusercontent.com/63577117/99965786-5e59a680-2dbb-11eb-9fb0-bac5b6cfe988.jpg)

The sample for reference can be found below.
[plotbandreference.zip](https://github.com/syncfusion/flutter-examples/files/5583173/plotbandreference.zip)

Please check with the above sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by chongbo2013** [comment]
thank you

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/100064618-bc46c680-2e6d-11eb-85d0-76630891dc4f.png)
How to display the group name on the prompt, and the display is different from the y-axis

**Comment by SriramKiranSenthilkumar** [comment]
Hi @chongbo2013,

We have analyzed on your query at our end and we would like to share some information regarding the TrackballBehavior available in the chart with which you can be able to display the data points value along with its series name on user interaction.  To achieve this, you need to enable the **`TrackballBehavior`** in the chart and set the **`tooltipDisplayMode`** property of the **`TrackballBehavior`** as **`TrackballDisplayMode.groupAllPoints`** and also set the name for each series so that its name will be displayed in the trackball's tooltip. Also in order to customize the format of the axis labels of the chart axis, you can use the **`labelFormat`** property of the chart axis. Please refer the code snippet below for further reference.
```
SfCartesianChart(
            primaryXAxis: NumericAxis(),
            primaryYAxis: NumericAxis(
                // To customize the axis label format
                labelFormat: '{value}%'),
            trackballBehavior: TrackballBehavior(
                // Enabled trackball for the chart
                enable: true,
                // Setting tooltip display mode as group all points.
                tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
            ),
            series: <ChartSeries<_ChartData, double>>[
              LineSeries<_ChartData, double>(
                  // setting name for the first series
                  name: 'allUsage',
                  dataSource: chartData1,
                  xValueMapper: (_ChartData data, _) => data.x,
                  yValueMapper: (_ChartData data, _) => data.y1,
                  markerSettings: MarkerSettings(isVisible: true)),
              LineSeries<_ChartData, double>(
                   // setting name for the second series
                  name: 'appUsage',
                  dataSource: chartData2,
                  xValueMapper: (_ChartData data, _) => data.x,
                  yValueMapper: (_ChartData data, _) => data.y2,
                  markerSettings: MarkerSettings(isVisible: true))
            ]
)
```
**Screenshot :**
![Screenshot_20201125-125324](https://user-images.githubusercontent.com/63577117/100199384-23728280-2f23-11eb-8714-83fe4a4e6a87.jpg)

The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5595207/tooltipgrouppoints.zip)

Please check with the above -attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/102195468-999e4f80-3ef9-11eb-881a-430e710f8279.png)
If the fixed-point data exceeds 100,000, the interface is densely packed with data points, causing the page to freeze, can it be optimized?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @chongbo2013,

We have analyzed your scenario at our end and if you want to render a large number of data points in the chart then we request you to use the fast line series because the rendering performance of the fast line series is faster. We hope that the fast line series will be highly helpful in your case. 

Also to mention that we are still continuously working on our end to improve the performance of our chart widget furthermore. However, we have also considered your suggestion at our end and will provide necessary improvements for our chart widget in order to improve the rendering performance in our upcoming releases. 

Please get in touch with us if still have further concerns.

Regards,
Sriram Kiran

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/103126716-24d1cf00-46ca-11eb-916b-8bf96e15c45e.png)
Hello, click back to cover the text

**Comment by SriramKiranSenthilkumar** [comment]
Hi @chongbo2013,

We have analyzed your scenario with the provided information at our end and we tried to replicate the reported issue with trackball tooltip and even with its builder. Unfortunately, we are not able to replicate the reported issue regarding the trackball tooltip markers gets overlayed on the trackball tooltips. Since we are not exactly sure on what scenario the issue is replicating, we kindly request you to try to replicate the reported issue with the below-attached test sample and revert us with it so that it will be helpful in further analysis to provide the solutions sooner.
Test sample: [testsample.zip](https://github.com/syncfusion/flutter-examples/files/5751519/sample.zip)

Regards,
Sriram Kiran

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/104287714-ce4df880-54f1-11eb-8d0d-11491ef9636d.png)
Hello, how to use interpolation, when the mouse is clicked, the current value is automatically calculated
thank you.

**Comment by Dharanipalani** [comment]
Hi @chongbo2013,
 
We would like to inform you that you can use the crosshair feature in our charts to know the current value of the axis when the mouse is clicked or if you want to know about the data-related information of the clicked points, you can use the trackball feature.  
 
To know more about trackball and crosshair, kindly refer to the below link.

[https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair](url) 
 
And we would like to let you know that, if you have a new query, kindly create a new GitHub issue or you can create an incident from the below link, this will be better for follow-up.

[https://www.syncfusion.com/support/directtrac/incidents/newincident](url)

Kindly revert us if you need any further assistance.  
 
Thanks,  
Dharanitharan. P

**Comment by chongbo2013** [comment]
Thank u very much&nbsp;





------------------ Original ------------------

**Comment by dharanidharandharmasivam** [comment]
Hi @chongbo2013 ,

Most welcome. Kindly get back to us if you need further assistance.

Thanks,
Dharani.

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/105655488-1c53fa80-5efb-11eb-9a86-d08f5463a066.png)
Hello, I used a trackball, but the effect I want is to calculate the value anywhere, not only when the y-axis has a value
