### ISSUE TITLE
[bar_with_track.dart] How can we give fix height of Bar? and How to make scrollable when there are more entries?

### ISSUE THREAD

**Issue by Pinkal7600** [syncfusion/flutter-examples#241]
**How can we give fix height of Bar?** 
- In the bar chart how can we provide static height. For example. As per the below image, I want to fix the height of the bar as 40 each. Currently, it is wrap and the height changes as per the view render. So, How we can do this in the bar_with_track.dart example.

**How to make scrollable when there are more entries?**
- Once we provide fix height to each bar. Then how can we make the graph vertical scrollable when there are more entries? Like in the below example we have 6 entry and when we have more than 10 entry in that the bar height should remain the same and the list should be scrollable.

**Example:**
<img src="https://user-images.githubusercontent.com/22210038/100840132-73a99180-349b-11eb-8388-2a72b117633d.png" width=270 height=460>

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Pinkal7600,

Greetings from Syncfusion. We have analyzed your queries at our end and provided the responses below.

**Query-1 : (How can we give fix height of Bar?)**

We have analyzed the above query with the provided information and we would like to share some information regarding the bar series. Every bar in the chart will get rendered only according to the provided y values returned to the **yValueMapper** function of the chart series. This is the default behaviour. 
Also, we have created a simple bar chart sample and attached at the end of the response in which we have enabled trackers for bar series and provided the same y values for all the bar in the chart and provided a minimum and maximum range for the y-axis so that the trackers for all the bar will be rendered to the provided range. 

Also, we would like to know whether you need to change the width and spacing of the bar series in the chart or if you need to provide fixed height for all the or if you think that we have misunderstood you query then, we kindly request you to share us with more information on your requirement in detail along with competitors example screenshots or screen recordings so that it will help provide the solutions sooner. 

**Query-2 : (How to make scrollable when there are more entries?)**

We have analyzed the above query with the provided information and the requested scenario regarding making the graph vertical scrollable when there are more entries can be achieved with the help **zoomPanBehavior** (zooming and panning user interaction) and the **visibleMinimum** and **visibleMaximum** properties of the chart axis available in the chart widget. We have also enabled zooming and panning feature in the below-attached sample and provided the visible range for the chart to view the first 5 bars in the chart. So, if you want to view the next 5 bars, you can scroll/pan the chart vertically.

For further reference on the **ZoomPanBehavior** feature, **visibleMinimum** and **visibleMaximum** properties, please check the user guides below.
-https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-maximum
- https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-maximum
- https://help.syncfusion.com/flutter/cartesian-charts/zoom-pan

Please get in touch with us if you require further assistance on this.

Bar sample: 
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5637638/sample.zip)

Please check with above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran
