### ISSUE TITLE
Event calendar / Ressource view : keyboard missing on flutter web

### ISSUE THREAD

**Issue by rachonzedev** [syncfusion/flutter-examples#246]
When  i click on the  calendar to add event, it is impossible to write the event title because the keyboard is pushed out of the screen... it’s impossible to create event... 😭

test on ipad : 

https://flutter.syncfusion.com/#/event-calendar/resource-view

Thanks

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Keyboard missing on calendar in Flutter web sample**” and it is working fine as expected from our end. We have attached the tested images and video for the same. Please find the images and video from the following link.

**Link:**
https://www.syncfusion.com/downloads/support/directtrac/308480/ze/Image_Video-1762902372.zip

**Tested device details:**

•	iPad Air -7th generation (Simulator version – 13.3)
•	iPad Air pro – 7th generation (Simulator version – 13.3)

If possible, can you please share the below details with us,

•	Issue reproducing video
•	iPad details

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by rachonzedev** [comment]
Hi,

Thanks for you reply, but the problem is the same...

I've done another test on a iPhone SE 2020 (13.5.1) with chrome and Safari, same problem as my first test on my iPad 7. I've also tested on iPhone 12 pro max iOS 14.3 simulator : same problem.

Step to reproduce : 
1. Open 'https://flutter.syncfusion.com/#/'
2. Choose 'Event calendar / Ressource view'
3. Click a case to create an event, the dialog will be shown
4. Click on 'Add Title' zone with your finger
5. The virtual keyboard will appears and disappear /!\ WITHOUT DOING ANYTHING.../!\

Conclusion : it 's impossible to write the title of the event...

To finish, I will repeat, the problem is only with flutter **web**.

I've done a video on my iPhone SE 2020 with chrome for example, you will find it with this post.

https://user-images.githubusercontent.com/60961162/103090441-4a3eda00-45f1-11eb-87c6-ee16f5b750de.mp4

Thank you,

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are validating this issue “**Keyboard missing on calendar in Flutter web sample**” in sample level. We will validate and update you the further details on or before December 31, 2020. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for your patience.

We have checked the mentioned issue “**Keyboard missing on the calendar in Flutter web sample**” and we are able to reproduce the issue from our end. When clicking the text field, the keyboard was hidden in a mobile browser, which is due to the architecture issue in Flutter. We have reported the issue on GitHub. If we got any solution from GitHub, we will update to you. We appreciate your patience until then.

**GitHub link:**
https://github.com/flutter/flutter/issues/73171

Regards,
Indumathi R

**Comment by 1rach** [comment]
There is a workaround here : https://stackoverflow.com/a/54977554

But on Flutter 3.7, it seems to be fixed : https://github.com/flutter/flutter/issues/73171#issuecomment-1378237034

i suggest to update flutter SDK used by the event calendar ressource view sample here https://flutter.syncfusion.com/#/event-calendar/resource-view because this bug is present when i use the event calendar ressource view sample on iPhone SE 2020 today (march 2022).
