### ISSUE TITLE
Border radius plot area

### ISSUE THREAD

**Issue by stoppiNeobiz** [syncfusion/flutter-examples#264]
Hi, it's possible create a graphs like this? i want a rounded border only in a plot area container. Other question 
is it possible to start the chart not attached to the right and left edge?
Thanks.

https://ibb.co/cFYHtjY

**Comment by Dharanipalani** [comment]
Hi @stoppiNeobiz, 
 
Greetings from Syncfusion. We have analyzed your scenario at our end and find responses to your queries below. 

Query #1: Want a rounded border only in a plot area container  

Response: As of now, we don’t have the option to customize the plot area alone with a rounded corner. Instead of that you can place our chart widget as a child of a container and use borderRadius property in the decoration of the container to apply rounded border for whole our chart area. But we consider it as a feature request, and it will include in any of our upcoming releases. 

`Container( 
   decoration: BoxDecoration( 
    color: Colors.red, 
    // Applying circular radius as border to the container. 
    borderRadius: BorderRadius.circular(20) 
   ), 
   // Add our chart widget as child to the container 
   child: SfCartesianChart() 
) 
`
Query #2: Is it possible to start the chart not attached to the right and left edge? 

Response: You can achieve this behavior in two different ways. One is by using plotOffset property for x-Axis. It is worked based on the pixels value. The chart is rendered in the center by leaving space in left and right with the given plotOffset value. 
` primaryXAxis: NumericAxis( 
   //Plotoffset value to render the chart in the center by left 30 pixels space in left and right of the chart. 
   plotOffset: 30,  
  // Applying range padding as additional to left blank space in left and right of the chart.
  rangePadding: ChartRangePadding.additional, 
), 
`
Another method is to apply rangePadding for our chart. Given range padding as additional will add the interval to the right and left side of the axis of the chart. 

` primaryXAxis: NumericAxis( 
// Applying range padding as additional
  rangePadding: ChartRangePadding.additional, 
), 
`
And finally, if you would like to apply a rounded border for the data label, you can use the borderRadius property of dataLabelSettings.

`dataLabelSettings: DataLabelSettings(isVisible: true, borderRadius: 3),`

We have attached the sample and screenshot for your reference and kindly make use of it. Please revert us if you need any further assistance. 

Sample: [https://www.syncfusion.com/downloads/support/directtrac/general/ze/I311048_rounded_corner-208355502](url)

Screenshot: 

![image](https://user-images.githubusercontent.com/19763272/105037898-abd55580-5a84-11eb-9009-b6edcf3254c6.png)

Thanks
Dharanitharan. P
