### ISSUE TITLE
Flutter PDF for Web

### ISSUE THREAD

**Issue by imakevirtual** [syncfusion/flutter-examples#274]
**File('TextFlow.pdf').writeAsBytes(document.save())**

How to achieve the result of the above code in the Web platform. Because Flutter Web doesn't provide **IO** package. any other ways to do it?

**Comment by Anand3595** [comment]
Hi imakevirtual,

Thanks for contacting Syncfusion support.

We can download the output PDF directly in web platform instead of using File class(I/O support for non-web applications). 

Use the following code to download the generated PDF file in web platform.

1) Import the following packages in your main.dart file.
```
import 'dart:convert';
import 'dart:html';
```

2) Include the following code snippet after saving PDF document as list of bytes to download the PDF document in the web application (any browser).
```
//Download the output file
AnchorElement(
    href:
        "data:application/octet-stream;charset=utf-16le;base64,${base64.encode(bytes)}")
  ..setAttribute("download", "output.pdf")
  ..click();

```
Please find the documentation from https://help.syncfusion.com/flutter/pdf/getting-started#save-and-download-a-pdf-document-in-web and please find the guidelines from https://www.syncfusion.com/kb/11973/how-to-create-a-pdf-file-in-flutter-web-platform to create and save/download PDF in web platform.

Please let us know if you need any further assistance in this.

Regards,
Anand Panchamoorthi

**Comment by imakevirtual** [comment]
Got it. Thank you very much.
