### ISSUE TITLE
adding new samples in realtime chart is not animated

### ISSUE THREAD

**Issue by subzero911** [syncfusion/flutter-examples#288]
animationDuration only takes care about predefined data.
If I add new samples dynamically, it paints it harshly, not smooth. It looks ugly.
Demo (Timer is delayed to 5000 ms):

https://user-images.githubusercontent.com/12999702/109414049-d5599900-79c1-11eb-8d1f-ed293711f9b0.mp4

Graph axis scaling looks harsh too, and I didn't find a way to make transitions smooth. Even in your manual it looks harsh (on gif): https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-range-calculation

**Comment by subzero911** [comment]
update:
I checked your sample https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/user_interactions/add_point_on_click.dart

It's very strange.
It uses empty `setState()` instead of `updateDataSource` callback in order to redraw. And animation is smooth.
Seems like updateDataSource is buggy.

So, if I fix this example https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/real_time_charts/live_update/real_time_line_chart.dart in this way, it will work
![image](https://user-images.githubusercontent.com/12999702/109415579-86643180-79ca-11eb-816e-4ae5b487493a.png)

**Comment by Dharanipalani** [comment]
Hi subzero911, 
 
Thanks for the interest in our Flutter charts. We have analyzed your scenarios and we would wish to tell you that while updating, adding, or deleting using **updateDataSource** public method, the animation will not happen, and this is our default behavior. We have prohibited the animation of charts in the public method because of consideration of the performance of charts. We have introduced this public method to render the chart with lag in performance. While calling **setState** it **renders the whole chart**, and it lags in performance whereas using our public method **updateDataSource** it renders quickly by **processing only the updated or latest data alone**. If you want the initial rendering animation, you can achieve it by calling the **animate** public method. To know more about this animation, you can refer to the following Kb and help document. 

Kb: [https://www.syncfusion.com/kb/12205/how-to-animate-the-chart-series-dynamically-using-the-public-method-sfcartesianchart](https://www.syncfusion.com/kb/12205/how-to-animate-the-chart-series-dynamically-using-the-public-method-sfcartesianchart)
Help document: [https://help.syncfusion.com/flutter/cartesian-charts/series-customization#dynamic-series-animation](https://help.syncfusion.com/flutter/cartesian-charts/series-customization#dynamic-series-animation)
 
Please revert us if you need any further assistance. 
 
Thanks, 
Dharaniatharan. P

**Comment by subzero911** [comment]
Thanks for quick reply.
No, I don't need initial rendering animation. In my case I need to load instantly history (about 5000 points) and animated drawing of new data points added in realtime. But I don't want performance lags. How do I achieve it if you say that setState() is not the best way?

**Comment by Dharanipalani** [comment]
Hi @subzero911,

As we said early, we prohibit dynamic animation for the public method by considering the performance of the chart. We would like you to suggest using the [Fastline chart ](https://help.syncfusion.com/flutter/cartesian-charts/chart-types#fast-line-chart)for your scenario. Using this chart and calling setState will performs the dynamic animation without performance lag. Hope this will helps you and revert us if you need further assistance.

Thanks,
Dharanitharan. P

**Comment by subzero911** [comment]
Thank you for your suggestion.
But there's one more point. When I use animation, I can't remove old points from the left. Chart begins "dancing" (as seen in video I've attached).

**Comment by Dharanipalani** [comment]
Hi @subzero911,

This behavior is due to the dynamic animation which happens while calling **setState.** If you want to avoid animation while removing the data points you can assign the value to the **animationDuartion** as 0. Thus, the dynamic animation happens only while adding the data points and not while removing the data points. We have attached the sample and the screen record with this and please make use of it.

Sample: [G288-removing-live-datapoints.zip](https://github.com/syncfusion/flutter-examples/files/6074160/G288-removing-live-datapoints.zip)

Screen record: https://user-images.githubusercontent.com/19763272/109767166-2618fe00-7c1d-11eb-9bbc-d76cbbfbf4a8.mp4

Please revert us if you need any further assistance.

Thanks,
Dharanitharan. P

**Comment by subzero911** [comment]
But it makes the chart stretch, confusing the user.
Is it possible to show only the part of graph (the latest points), and delete the leftmost points outside the screen? So it wouldn't be noticable by user.

**Comment by Dharanipalani** [comment]
Hi @subzero911,

You can manually set the visible range for the graph using **visibleMinimum** and **visibleMaximum** properties in the chart. For your scenario, using the **onActaulRangeChanged** callback you can set the visible range for your charts. We have attached the sample for your reference with the manual visible range and you set it as per your wish. For more information, refer to the following help document. 

[https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-minimum](https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-minimum)
[https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onactualrangechanged](https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onactualrangechanged)

Sample: [live_update.zip](https://github.com/syncfusion/flutter-examples/files/6089045/live_update.zip)


You can set the visible range as per your wish and please revert us if you need any further assistance.

Thanks,
Dharanitharan. P
