### ISSUE TITLE
_updateSize no called after update margin (PDF)

### ISSUE THREAD

**Issue by cnksoft** [syncfusion/flutter-examples#297]
Hi team. First of all, thanks for this great extension again.

I have found a bug (I think).
If we try to change the margins with:

_document.pageSettings.margins.all = 0,0;
or
_document.pageSettings.setMargins(0,0);

the pagesize doesn't update. So, if after change margin we try to create a new page, this new page continues with the old margin.

Need to change orientation as following:
_document.pageSettings.orientation = PdfPageOrientation.landscape

and then create a new page, to effectively the new margin to be applied.

After that, we can again change orientation to portrait and the last margin modification are well applied.

I think this is due need to call _updateSize(_orientation); after update the margin size to re-calculate the correct size (the same way you call it after update orientation)

Note that pdf_page_settings.dart the _setMargins() is as follow:

LINE 28
  //Implementation
  void _setMargins(double margin) {
    left = top = right = bottom = margin;
  }

Perhaps only to replace by the following code:

LINE 28
  //Implementation
  void _setMargins(double margin) {
    left = top = right = bottom = margin;
    _updateSize(_orientation);
  }

I hope this can help you to solve this bug.

Again, thanks for your support.

César

**Comment by Anand3595** [comment]
Hi CNK Soft,

Thanks for contacting Syncfusion support.

We can reproduce the reported issue with “Page size is not updated properly when adding margins” in our end and it’s confirmed as a defect. We will include the fix in our upcoming weekly release which is planned on 16th March 2021.

The status of the bug can be track through below link: https://www.syncfusion.com/feedback/23240/page-size-is-not-updated-properly-when-adding-margins

Regards,
Anand Panchamoorthi

**Comment by cnksoft** [comment]
Thanks very much.
Excellent work.

Regards

**Comment by Anand3595** [comment]
Hi CNK Soft,

Thanks for your patience.

We have included the fix for the issue “page size is not updated properly when adding margins” in our weekly release V18.4.48-beta. And we have created a simple sample to update margins while creating PDF documents and shared for your reference https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_pdf_file-1285102333.

We can create or update page settings in two different ways.

1.	Directly add/update the page settings in the PdfDocument instance – In this case the page settings update is applied for newly added pages by creating sections internally. Refer the documentation for more details.
https://help.syncfusion.com/flutter/pdf/working-with-document#adding-the-document-settings. 
2.	Create separate sections and add the page settings – For this case, if the section is already contain pages, then the page settings update is not applied. We can only add the page settings before adding pages to the section. Refer the documentation link for more details. 
https://help.syncfusion.com/flutter/pdf/working-with-pages#adding-sections-with-different-page-settings.

Please let us know, If you need any further assistance in this.

Regards,
Anand Panchamoorthi
