### ISSUE TITLE
How to check if signature is empty or has a minimum sign.

### ISSUE THREAD

**Issue by khushi-shettigar** [syncfusion/flutter-examples#340]
I want to check if a signature is empty or not. I don't want to accept an empty signature.

**Comment by MeikandaNayanar** [comment]
Hi Khushi,

Thank you for contacting us. 

You can use the [onSignStart](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad/onSignStart.html) call back in the Signature Pad to identify whether the Signature Pad is empty or not. You can get the code snippets for this from the below link

https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/signature_pad/getting_started/signature_pad_getting_started.dart

In this sample, we are setting a boolean value in the `onSignStart `callback before converting the Signature as an image. If this boolean value is true, then there is a signature drawn in the Signature Pad otherwise it is empty. 

Documentation about the `onSignStart` callback - https://help.syncfusion.com/flutter/signaturepad/getting-started#handle-onsignstart-and-onsignend-callbacks

Please let me know if you need any further assistance in this.

Thanks
Meikandan

**Comment by khushi-shettigar** [comment]
Hello,

Thank you for the response. I will check this out.

Thank you
Kavana
