### ISSUE TITLE
testing pdf file if it has password

### ISSUE THREAD

**Issue by hussam132** [syncfusion/flutter-examples#352]
I use this packages to `syncfusion_flutter_pdf: ^19.1.64-beta` to set password for my pdf file so its possible to test if the pdf file has password and if yes then open pdf file with password and get file information 

I used this

`final sPDF.PdfDocument testdocument = sPDF.PdfDocument(  inputBytes: File(path).readAsBytesSync());`
in try and catch but I've got this error 
` Invalid argument (password): Cannot open an encrypted document. The password is invalid.: ""
`

**Comment by chinnumuniyappan** [comment]
Hi @hussam132 ,

Greetings from Syncfusion.

At present we do not have direct support to check whether the document is encrypted or not. Instead of we can get these details based on the error message as follows.

```dart
bool isEncryptedDocument(String fileName) {
  bool isEncrypted = false;
  try {
    //Load the encrypted PDF document.
    PdfDocument document =
        PdfDocument(inputBytes: File(fileName).readAsBytesSync());
  } catch (exception) {
    if (exception.toString().contains('Cannot open an encrypted document.')) {
      isEncrypted = true;
    }
  }
  return isEncrypted;
}
```
Please refer to the following UG documentation for more details about security. https://help.syncfusion.com/flutter/pdf/working-with-security 

Regards, 
Chinnu M
