### ISSUE TITLE
Calendar - When adding a new appointment, not the whole appointment is marked

### ISSUE THREAD

**Issue by ronytesler** [syncfusion/flutter-examples#377]
![image](https://user-images.githubusercontent.com/9344207/122624795-889de900-d0aa-11eb-9937-3f97b38457ac.png)
Only after clicking again it's OK:
![image](https://user-images.githubusercontent.com/9344207/122624803-918eba80-d0aa-11eb-81b0-b4f476e2a35e.png)

Not the best colors selection, but you can see the lighter blue.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: When adding new appointment, not whole appointment is marked.**

As per the Flutter Calendar implementation, when adding the new appointment using the onTap callback, the selection will appear for the cell and again you select, the selection will appear for the appointment and it is the expected behavior of the Flutter calendar.

Regards,
Indumathi R
