### ISSUE TITLE
How to add image in pdf if we are given a imageurl from network?

### ISSUE THREAD

**Issue by nouveau-riche** [syncfusion/flutter-examples#392]

**Comment by Anand3595** [comment]
Hi Nikunj Sharma,

Thanks for contacting Syncfusion support.

We have created a sample to read the image data from webspace/website and drawn the image using the retrieved image data. Kindly try the following code example and sample in your side and let us know whether the issue is resolved at your end.

1.	Add http package in dependencies section of pubspec.yaml file
```
dependencies:
  http: ^0.12.2
```

2.	Import the following package in your dart file.
`import 'package:http/http.dart' show get;`

3.	Get image data
```
//Read an image data from website/webspace
var url = "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg";
var response = await get(url);
var data = response.bodyBytes;
```

4.	Draw image in PDF
```
//Create a new PDF document
PdfDocument document = PdfDocument();
//Load an image from image data
PdfBitmap image = PdfBitmap(data);
//Draw image in page graphics
document.pages.add().graphics.drawImage(image, const Rect.fromLTWH(0, 0, 500, 200));
//Save and launch the document
final List<int> bytes = document.save();
//Dispose the document.
document.dispose();
```

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample-646187320

With Regards,
Anand Panchamoorthi

**Comment by nouveau-riche** [comment]
Thanks! Found it helpful
