### ISSUE TITLE
Unable to view pdf on first try

### ISSUE THREAD

**Issue by chrisoftech** [syncfusion/flutter-examples#400]
Currently installed syncfusion_flutter_pdfviewer: ^19.2.48-beta and when i try loading a pdf document using `SfPdfViewer.memory`, i get an exception saying `There was an error opening this document`.

On second attempt of loading the same document, it works but not on the first try (for all document cases i have tried).

**Comment by deepika134** [comment]
Hi chrisoftech,

Greetings from Syncfusion,

We suspect that the reported issue might be due to improper document byte used in SfPdfViewer. 
If the document byte is null, similar issue might be occurred and document load failed callback will be triggered with "There was an error opening this document" information. 
To know more about this callback, please refer the following link.
https://help.syncfusion.com/flutter/pdf-viewer/getting-started#document-load-failed-callback  

We have prepared a sample for load a PDF document using SfPdfViewer.memory() for your reference, which can be downloaded at the following link,
https://www.syncfusion.com/downloads/support/directtrac/337035/ze/flutter_app337035-1983870785.zip  
If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing sample which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika R

**Comment by chrisoftech** [comment]
Thanks for your feedback. Unfortunately, i was unable to access the zip file. I got an Access Denied error when i tried login.

Here's the full message
Access Denied
You don’t have permission to access this file. The reason may be:
The incident associated with this file is not tied to the account you used to log in. To Logout use this link.
Your enterprise portal admin has not allowed you to access other portal users’ incidents. Ask admin to change the support visibility in their Syncfusion profile.
If you feel this information is wrong and you need to download this file, please contact us.

**Comment by deepika134** [comment]
Hi chrisoftech,

Sorry for the inconvenience,
Please find the sample in the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app337035360960875.zip
Regards,
Deepika R

**Comment by chrisoftech** [comment]
Hello @deepika134 

Thanks for your assistance,

With a bit of research, i noticed the issue was not with the pdf-viewer but with the file picker (returning null or incomplete byte data on first pick).

Resolved this.
