### ISSUE TITLE
how to add pdf saving progress indicator

### ISSUE THREAD

**Issue by ravidewanga** [syncfusion/flutter-examples#402]

**Comment by Anand3595** [comment]
Hi @ravidewanga ,

Thanks for contacting Syncfusion support.

Our package is written natively in Dart for supporting all the platforms and its only works on the main thread (synchronously) and we do not have asynchronous support, due to the UI has been stopped animating for doing very large process. So we request you to use the Isolate to overcome issue. Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/PdfSample1931322068 for more details.

With Regards,
Anand Panchamoorthi
