### ISSUE TITLE
Issue with SplineSeries

### ISSUE THREAD

**Issue by sujalBandhara** [syncfusion/flutter-examples#42]
![Screen Shot 2019-10-08 at 4 48 34 PM](https://user-images.githubusercontent.com/1314211/66391719-82a5c880-e9eb-11e9-9e9c-93114227f0b9.png)
Issue when used SplineSeries and value is near about zero then graph not display proper.

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

Greetings from Syncfusion. If you render the spline series, by default natural spline type will be rendered. In natural spline the curve will go to negative range depends on the data and this is the behavior of natural spline. If you wish to see the curve, then you can increase the negative range for the y-axis as below, so that you can see the entire curve.

> 
    SfCartesianChart(
          primaryYAxis: NumericAxis(
               minimum: -10
          ),
    )

You can find the [screenshot](https://imgur.com/xoHDGsX). We are also having different spline types, you can check from [here](https://help.syncfusion.com/flutter/chart/cartesian-chart-types#spline-rendering-types).

Thanks,
Dharani.

**Comment by sujalBandhara** [comment]
@dharanidharandharmasivam Thanks for the answer.
