### ISSUE TITLE
Caledar: TimeSlotViewSettings timeIntervar fails with diferents startHour/endHour configuration

### ISSUE THREAD

**Issue by arturoblack** [syncfusion/flutter-examples#429]
Hello.
the timeInterval fails when you try to start a interval  whit a startHour diferent to  12:00

by example
if you set 
 `timeInterval: const Duration(minutes: 45),`
the result is:

> 12:45
> 1:30
> 2:15
> 3:00 
> ...
> 6:45
> 7:30 
> 8:15
> etc

this is ok

if you set
```
timeInterval: const Duration(minutes: 45),
startHour: 7.5, // 7:30 AM -> valid interval for 45min timeInterval starding in 12:00
```
the result is:

> 8:15
> 9:00
> 9:45 etc
> this is ok

but if you set
```
timeInterval: const Duration(minutes: 45),
startHour: 7.0, // 7:00 AM -> invalid interval for 45min timeInterval starding in 12:00
```
the result is:

> 8:48 // add 48 min?
> 9:36
> 10:24
> 11:12 etc

this is wrong

with diferent endHour configuration the interval gets even weirder.

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information we have checked the mentioned issue **"Fails the timeInterval when tried to start a different startHour and timeInterval"**, based on the calendar implementation when the given timeinterval doesn’t divide the total available hours equally we will calculate the nearest possible value for the timeinterval, so that it will divide equally.

In your case when we set the start hour as 8 and interval as 45 mins, if we divide with the given duration it will end on 11.45 PM and 15 will be left for that day so to avoid this we have added calculation to get the nearest rounded value so that it will display as 8.48 AM as start hour.

In your case, if we set the end hour as 23.75 the end time will be 11.45 PM and the timeslot will display as 8.45 as per your requirement.

Kindly find the UG document for the same by referring to the following link:
https://help.syncfusion.com/flutter/calendar/timeslot-views#flexible-working-days-and-working-hours

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K
