### ISSUE TITLE
[SfCalendar] How to change the color of the Appointment Indicator in a MonthCell ?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-examples#436]
Where do I define the color of that indicator dot? 

When I initially set up the Calendar, it had a specific color of an element inside the Appointment. Now these indicators are all grey but I don't know why.

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: How to change the color of the Appointment Indicator in a MonthCell ?**

As per the implementation of the calendar, the indicator color is applying from the corresponding appointment color, since it’s the appointment indicator it is the behavior. In the shared information, you have specified indicators are all in Grey color, if possible, can you please check the appointment color once and let us know. If still, you are facing the same issue, please share more details about your requirement clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
