### ISSUE TITLE
pont.y does not work

### ISSUE THREAD

**Issue by maitycyrus** [syncfusion/flutter-examples#478]
Setting the format property like:

```
 tooltipBehavior: TooltipBehavior(
	enable: true,
	format: "point.y",
),
```
will literally show the string "point.y" but not the value of point.y.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @maitycyrus 

Greetings from Syncfusion. We have analyzed your query, and we have tried to reproduce the reported issue regarding format point.y is not working in the tooltip behavior. But the reported issue is not getting reproduced at our end and in the tooltip, the y value is showing properly. We have attached the sample below which is used in the test phase.

Code snippet:

```dart
tooltipBehavior: TooltipBehavior(
       enable: true,
       format: "point.y"
),
```

Screenshot:

![image](https://user-images.githubusercontent.com/61863686/142024461-f650e333-e229-4d6a-ac30-a652e0b2f2af.png)


Sample: [github_478.zip](https://github.com/syncfusion/flutter-examples/files/7548139/github_478.zip)


Since we are not aware of your exact scenario in which the reported scenario is occurred, kindly try to reproduce the reported issue in the attached sample and get back to us with the replication steps.


Regards,
Yuvaraj.
