### ISSUE TITLE
select the first line by default

### ISSUE THREAD

**Issue by Cyycl** [syncfusion/flutter-examples#54]
There are multiple lines, I want to select the first line by default, how can I do it?

Thanks~~

**Comment by dharanidharandharmasivam** [comment]
Hi @Cyycl ,

Thanks for using our Syncfusion Flutter chart widget. Your requirement for selecting the line can be achieved using **initialSelectedDataIndexes** of series property. Here you need to pass the point index value to select the segment. You can find the code snippet below in which we have passed all the point index value using a loop since your requirement is to select the first series. You can change this based on your requirements.

>    
     SfCartesianChart(
        series: <CartesianSeries>[

            LineSeries<ChartData, String>(
              
                // Specify the point index value
                initialSelectedDataIndexes: dataSelection,

                selectionSettings: SelectionSettings(
                  enable: true,
                  selectedColor: Colors.red,
                  selectedBorderWidth: 4
                )),

            LineSeries<ChartData, String>(
                //...
            ),

            LineSeries<ChartData, String>(
                //...
            ),
          ],
        )

For your convenience, we have attached the [sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/selection-1550983215).

Hope this helps.

Thanks,
Dharani.

**Comment by Cyycl** [comment]
thanks, @dharanidharandharmasivam. 

Thank you very much for the example, but the example display is not what I want.

I want to show the selected line by default, and the rest don't show.
As show below，MB is selected by default，MM and BB are not selected，so MB is only showed.


![](https://s2.ax1x.com/2019/11/06/MPIFv4.jpg)

**Comment by dharanidharandharmasivam** [comment]
Hi @Cyycl ,

Thanks for your information. You can hide the series using the **isVisible** property. By default, the **isVisible** property of the series will be true, if you set this to false then the series will be hidden. Find the [sample ](https://www.syncfusion.com/downloads/support/directtrac/general/ze/series_visibility-2048051504) and code snippet below to achieve this.

>  
     SfCartesianChart(
          series: <CartesianSeries>[
            LineSeries<ChartData, String>(
                name: 'MB'),
            LineSeries<ChartData, String>(
                isVisible: false,
                name: 'MM'),
            LineSeries<ChartData, String>(
                isVisible: false,
                name: 'BB')
          ],
        )

Thanks,
Dharani.
