### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kendginwff** [syncfusion/flutter-examples#550]
when i use SfCartesianChart  in flutter , after setState again and again , memory leak !
setState one time then the memory up 15MB bigger

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @kendginwff,

We strongly recommend the updateDataSource method instead of setState to update the data source dynamically in the chart, it will process and render updated points alone instead of updating the whole chart. We have provided the demo sample and UG link for your reference.

Sample: https://flutter.syncfusion.com/#/cartesian-charts/real-time-charts/live-updates/real-time-line-chart

UG: https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource

We have ensured the memory leak in windows application, but the memory leaks is not as you said. Since we are not aware of your exact scenario, kindly get back to us with the below information, this will be helpful in further analysis.
* Type of series and number of series using in chart
* If you are updating the chart in live, provide the time interval for updating the chart
* Platform you have found the memory leak
* Ensure you are using the latest version of chart widget
* Share the entire code you are using or get back to us by replicating your scenario with above sample
* If possible share the screenshots for the memory leak

Regards,
Yuvaraj.
