### ISSUE TITLE
view = CalendarView.schedule, How to get Scroll related data? And there is an error when change view mode while scrolling in schedule view.

### ISSUE THREAD

**Issue by dmk3141618** [syncfusion/flutter-examples#555]
### 1. While scrolls in CalendarView.schedule, change view to CalendarView.month then it makes error.

<img width="2177" alt="image" src="https://user-images.githubusercontent.com/81060569/156746740-07fdc8ab-8939-42a6-a3d5-9ade387dcf34.png">

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/81060569/156750440-b3deebf5-f9ba-4e13-b9ba-c5ce565fffcb.png">

### 2. How to get displayDate while scrolling (scrolling means changing month) on schedule view?

In case of month view, If scrolls horizontally, then be able to get related data  on the onViewChanged.
But schedule view, it doesn't do anything while scrolling. 
But in the _handleScheduleViewScrolled() code, there is this code.
_controller.displayDate = currentViewDate;

How can I get the related data of the changes of schedule view scrolling?

```
  void onViewChangedCalendar(ViewChangedDetails viewChangedDetails) {
    if (calendarController.view == CalendarView.month) {
      SchedulerBinding.instance!.addPostFrameCallback((Duration duration) {
        final changedDate = viewChangedDetails
            .visibleDates[viewChangedDetails.visibleDates.length ~/ 2];
        headerDisplayDate.value = changedDate;
      });
    } else if (calendarController.view == CalendarView.schedule) {
      SchedulerBinding.instance!.addPostFrameCallback((Duration duration) {
        headerDisplayDate.value = calendarController.displayDate!;
      });
    }
  }
```

```
  /// Called in the following scenarios when the visible dates were changed
  /// 1. When calendar loaded the visible dates initially.
  /// 2. When calendar view swiped to previous/next view.
  /// 3. When calendar view changed, i.e: Month to day, etc..,
  /// 4. When navigated to a specific date programmatically by using the
  /// [controller.displayDate].
final ViewChangedCallback? onViewChanged;
```

_handleScheduleViewScrolled()

```
          /// Check the view have intersection point, because intersection point
          /// tells the view does not have similar month dates. If it reaches
          /// the intersection point then it moves to another month date so
          /// update the header view date with latest date.
          if (interSectionPoint != -1 &&
              -scrolledPosition <= interSectionPoint) {
            date = DateTimeHelper.getDateTimeValue(addDays(date, 6));
          }

          final DateTime currentViewDate = DateTimeHelper.getDateTimeValue(
              getValidDate(widget.minDate, widget.maxDate, date));
          _currentDate = currentViewDate;
          if (currentViewDate.month != _headerUpdateNotifier.value!.month ||
              currentViewDate.year != _headerUpdateNotifier.value!.year) {
            

> _controller.displayDate = currentViewDate;

            _headerUpdateNotifier.value = currentViewDate;
          }
```

**Comment by Indumathi1195R** [comment]
Hi ,

**Regarding Query: While scrolls in CalendarView.schedule, change view to CalendarView.month then it makes error.**

We have checked with changing the CalendarView.month from CalendarView.schedule while scrolling and we are unable to reproduce the any exception or error from our end. If possible, can you please share more below about the exception clearly?

•	Code snippet
•	Issue reproducing video
 
 It would be helpful for us to analyze and provide you a solution at the earliest.

**Regarding Query: How to get displayDate while scrolling (scrolling means changing month) on schedule view?**

As per the current implementation of the Calendar schedule view, OnViewChanged callback doesn’t work in schedule view. Because we can’t identify the view changes properly for triggering the onViewChanged callback to below scenarios. So, we can’t get the details in schedule view.

1. Month header reaches the top position.
2. End of each month.
3. While loading months in the current view.

We hope that this information helps you. Please get in touch with us if would you require any further assistance.

Regards,
Indumathi R

**Comment by dmk3141618** [comment]
Thank you very much.

1. While scrolls in CalendarView.schedule, change view to CalendarView.month then it makes error.
<== This only occurred in debug run mode.

2. How to get displayDate while scrolling (scrolling means changing month) on schedule view?3. 
<== Do you mean that I can get the solution to use this scenario? Or means that it can not get the solution?
Month header reaches the top position.
End of each month.
While loading months in the current view.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Q1:**

We have checked the sample with the debug mode and there is no error from our end. If possible please share the below details to us.

•	Code snippet
•	Issue reproducing video

It would be helpful for us to analyze and provide you a solution at the earliest.

**Regarding Q2:**
onViewChanged callback doesn’t triggered in schedule view while scrolling. So we can get the details using the onViewChnaged callback. We hope that this information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
