### ISSUE TITLE
Click Event on agenda Meetings

### ISSUE THREAD

**Issue by ramaraju235** [syncfusion/flutter-examples#592]
Hi, 

We would like a click event for meetings on agenda for a date in month calendar view. so that we can show some other page based on the meeting user clicks on.

If it is already available please guide me on how to implement it.

Thanks & Regards,
Rama Raju

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: We would like a click event for meetings on agenda for a date in month calendar view. so that we can show some other page based on the meeting user clicks on.**

Based on the shared information, we have checked and your requirement is “**To show the tapped agenda appointment in another page in the Flutter Calendar**”. We have a KB documentation for the same. Please find the KB documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/12358/how-to-show-the-tapped-appointment-details-on-another-page-in-the-flutter-calendar 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
