### ISSUE TITLE
some of the labels did not show in piechart

### ISSUE THREAD

**Issue by didyqian** [syncfusion/flutter-examples#60]
I run the pie with smart labels demo, it set eight labels, but only show six, how to fix this?

![微信图片_20191129103505](https://user-images.githubusercontent.com/31534014/69839814-12e9e680-1294-11ea-9d5c-7e8288e8f221.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @didyqian ,

Greetings from Syncfusion. We have analyzed your query and we would like to let you when the data label position moves out of the chart area or the labels got intersected, the label will be hidden, this is our default behavior. If you wish to make all the labels visible, then specify the labelIntersectAction to none so that all the labels will be visible. Then you can specify the radius to the pie series using the radius property to modify the size of the pie chart so that all the labels will be visible within the chart area and the default value is 80%. This can be modified based on your scenario. Find the code snippet below for the above scenario.

> 
       SfCircularChart(
            series: <PieSeries<_PieData, String>>[
              PieSeries<_PieData, String>(
                  dataLabelSettings: DataLabelSettings(
                      isVisible: true,
                      labelIntersectAction: LabelIntersectAction.none))
            ],
          ),


Sample for reference can be found from below link.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample182405109 

Thanks,
Dharani.

**Comment by didyqian** [comment]
> isVisible

Thank you for your reply！

**Comment by guiinfo3333** [comment]
Obrigado, Dharani.
