### ISSUE TITLE
Special region widget is coming behind appointments

### ISSUE THREAD

**Issue by MDSADABWASIM** [syncfusion/flutter-examples#603]
HI, I am passing appointmentsDataSource which has multiple appointments to SfCalendar, and I want to block one of the appointments, so I'm using special regions for it, but its widget is coming behind the appointments.

```
SfCalendar(
      showNavigationArrow: model.isWebFullView,
      controller: calendarController,
      showDatePickerButton: true,
      allowedViews: _allowedViews,
      specialRegions: regions,
      blackoutDatesTextStyle: mediumTextStyle,
      timeRegionBuilder: _getSpecialRegionWidget,
      timeSlotViewSettings: const TimeSlotViewSettings(
          minimumAppointmentDuration: Duration(minutes: 30)),
      dataSource: dataSource,
      onTap: calendarTapCallback,
    );
```

is there any other way to block any particular timing of a day(ex: today 8.00 - 8.30 pm)?

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation of the calendar, time regions are shown behind the appointment, and it is the expected behavior. Also, we have already logged the feature request for “Providing support for read only appointments in Flutter Calendar (SfCalendar)”. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.
 
Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using this Feature Report page. 

**Feedback link:** https://www.syncfusion.com/feedback/31761/providing-support-for-read-only-appointments-in-flutter-calendar-sfcalendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by MDSADABWASIM** [comment]
Thanks, @Indumathi1195R for clarification.
