### ISSUE TITLE
Gauge annotation does not show up v17.3.26-beta

### ISSUE THREAD

**Issue by simeon9696** [syncfusion/flutter-examples#62]
I'm new to syncfusion and I've been trying to create a simple gauge. Everything else was rendered except the gauge annotation when I did my own code, so I tried the example (in a separate project with just the gauge) and got the same issue. Sometimes I see the annotation sometimes but it disappears immediately. There are also no errors thrown. The `Container` widget here is a child of `<Widget>[]` which itself nested inside a `Column` widget

```
          Container(
            child: SfRadialGauge(
              axes: <RadialAxis>[
                RadialAxis(minimum: 0, maximum: 150,
                  pointers: <GaugePointer>[MarkerPointer(
                    markerType: MarkerType.invertedTriangle,
                    markerOffset: -5,
                    enableAnimation: true,
                    animationDuration: 0.5,
                    value: 90,
                    color: Colors.pink,
                    )
                  ],
                  annotations: <GaugeAnnotation>[
                    GaugeAnnotation(
                      widget: Container(
                        child:Text('90', style: Theme.of(context).textTheme.body1),
                      ),
                      angle: 90,
                      positionFactor: 0.5,
                      horizontalAlignment: GaugeAlignment.center,
                      verticalAlignment: GaugeAlignment.center,
                    )
                  ]
                )
              ]
            ),
          ),

```

Github refused to upload the image of the rendered output so:
[Rendered Output](https://www.flickr.com/photos/154701843@N07/49233749038/in/dateposted-public/lightbox/)

**Comment by sheiksyedm** [comment]
Hi Simeon, 

Thanks for your interest in our Syncfusion flutter radial gauge widget. We have analysed on the reported scenario and tried to replicate at our end. Unfortunately, the issue is not reproduced at our end, the annotation showing properly. As you suggest, we've tried code below.

`void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData(
          brightness: Brightness.dark
        ),
        home: MyHomePage()
    );
  }
}
class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Bluetooth Disabled',style: Theme
                .of(context)
                .textTheme
                .body1),
            Container(
              child: SfRadialGauge(
                  axes: <RadialAxis>[
                    RadialAxis(minimum: 0, maximum: 150, interval: 10,
                        pointers: <GaugePointer>[MarkerPointer(
                          markerType: MarkerType.invertedTriangle,
                          markerOffset: -5,
                          enableAnimation: true,
                          animationDuration: 0.5,
                          value: 90,
                          color: Colors.pink,
                        )
                        ],
                        annotations: <GaugeAnnotation>[
                          GaugeAnnotation(
                            widget: Container(
                              child: Text('90', style: Theme
                                  .of(context)
                                  .textTheme
                                  .body1),
                            ),
                            angle: 90,
                            positionFactor: 0.5,
                            horizontalAlignment: GaugeAlignment.center,
                            verticalAlignment: GaugeAlignment.center,
                          )
                        ]
                    )
                  ]
              ),
            ),
            Text('Launch notif',style: Theme
                .of(context)
                .textTheme
                .body1)
          ],
        )
      ),
    );
  }
}
`
Output: 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/23059975/71073191-e3990c00-21a5-11ea-8cad-676274fd705f.png">

Use the code above if the annotation works correctly. Since we are not aware on the exact scenario, kindly share your complete code that will be helpful in further analysis and provide you the solution sooner.

Tested version: 
Flutter (Channel stable, v1.12.13+hotfix.5)
Both v17.3.26-beta and v17.4.49-beta

**Comment by simeon9696** [comment]
Upgrading to 17.4.40-beta has solved my issue. Thank you!
