### ISSUE TITLE
[iOS] could not navigate throw month by arrow

### ISSUE THREAD

**Issue by adamsony06** [syncfusion/flutter-examples#622]
Hello,

I have a problem with your widget, it's very well made ! So I tried to test the calendar picker for iOS but the problem is that you can't change month by clicking on the arrow key (like shown on the screenshot). Is that a problem of misconfiguration of the plugin or in the code ?

Thanks !
Best regards Adam HARMAND.

<img width="481" alt="Capture d’écran 2022-05-20 à 12 09 38" src="https://user-images.githubusercontent.com/58440550/169506385-f5085015-91e5-46cc-92ab-f3ddae2d5343.png">

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “Navigation arrow not working in the Flutter DateRangePicker for iOS platform”. As per the shared image, we suspect you are using minDate and maxDate properties for SfDateRangePicker, so beyond those dates you can’t navigate, and it is the expected behavior, otherwise the arrows working fine as expected. We hope that this information helps you. Please get in touch with us if would you require any further assistance.

Regards,
Indumathi R

**Comment by adamsony06** [comment]
Thank you for you quick response ! It stills not working in iOS, I have the version 18.4.46.

Regards Adam.
