### ISSUE TITLE
can't build project, pls fix this

### ISSUE THREAD

**Issue by NinhPhamHai** [syncfusion/flutter-examples#625]
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.57/lib/src/date_picker/date_picker.dart:8059:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.57/lib/src/date_picker/date_picker.dart:9826:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “**Error occurred while using the addPostFrameCallback in the Flutter DateRangePicker**”. We have checked the mentioned issue in 20.1.57 version and we are unable to reproduce the mentioned issue from our end.  Also, can you please confirm if you are using the latest flutter version? Otherwise, kindly update to the latest flutter version and check still if you are facing same issue. 

Regards,
Indumathi R
