### ISSUE TITLE
how to  display text widget when particular bar  has zero data

### ISSUE THREAD

**Issue by gopibathini** [syncfusion/flutter-examples#653]
unable to find the option to display widget of text  in place of graph bar  which has zero value ha
xaxis :integer and y axis : Strings
![chart](https://user-images.githubusercontent.com/89006280/178952303-c093ffc9-2864-4b54-a787-ef83b8c6aa5a.PNG)

**Comment by gopibathini** [comment]
if we can use data label setting in particular series we can use  our widget

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @gopibathini,

Greetings from Syncfusion. We suggest you the builder property in the data label settings, here you can render a customized widget instead of a data label. Using this you can replace the data label with a customizable widget based on the y value from that builder function. We have attached the code snippet and sample to achieve your requirement.

Code snippet:
![image](https://user-images.githubusercontent.com/61863686/179282400-c33ee3bd-7df0-46b7-95b7-c43b55027065.png)

Sample: 
[i392201.zip](https://github.com/syncfusion/flutter-examples/files/9123011/i392201.zip)


Regards,
Yuvaraj.
