### ISSUE TITLE
 No named parameter with the name 'thumbVisibility'

### ISSUE THREAD

**Issue by ehsan097** [syncfusion/flutter-examples#654]
../../../Documents/futter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.2.38/lib/src/legend/legend.dart:666:11: Error: No named parameter with the name 'thumbVisibility'.
          thumbVisibility: widget.shouldAlwaysShowScrollbar,
          ^^^^^^^^^^^^^^^

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ehsan097,

We have tried to reproduce the reported scenario with syncfusion_flutter_charts with version 20.2.38 but were unable to reproduce the issue at our end. We suspect it is due to a cache issue. We suggest you clean the project and try again. If you are still facing the same problem, please try to replicate the issue in the attached sample and revert to us, so that we can reproduce the problem and provide a solution earlier?

Sample: [i393254.zip](https://github.com/syncfusion/flutter-examples/files/9151580/i393254.zip)


Regards,
Yuvaraj.
