### ISSUE TITLE
SFRadial Guage marker is scroll conflit in listview and scroll view

### ISSUE THREAD

**Issue by mobilelocalteam** [syncfusion/flutter-examples#666]
When i use SfRadial guage with Markerpointer in normal page without scroll is working perfectly. But it not work perfectly in scrollable page.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @mobilelocalteam,

We have validated your query and we are able to replicate the reported issue at our end. We will consider this as a bug and logged a bug report for it. We will fix and include it in our upcoming Volume 3 main release which is expected to be rolled out by end of September. We will update you here once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @mobilelocalteam,

The reported issue regarding Vertical dragging gesture is not working properly when placing the SfRadialGauge inside scrollable widget has been fixed. But we are facing some automation breaks and due to these we can't be able to move this into our Volume 3 main release, we will give priority to this and include it in our weekly patch release, which is scheduled for 11th October 2022. We will let you know once the release gets rolled out. We appreciate your patience until then.

Regards,
Sriram Kiran
