### ISSUE TITLE
Memory leak in SfCartesianChart, SfRadialGauge, probably others when animation is enabled.

### ISSUE THREAD

**Issue by muhleder** [syncfusion/flutter-examples#67]
I've noticed a memory leak when animation is enabled, this affects at least SfRadialGauge and I believe other charts as well.

Demonstration app exhibiting the issue, https://gist.github.com/muhleder/9df9cf63ef4da9c7b7d5f4e62ecb8010
This is the flutter sample counter app, with a syncfusion radial guage from the examples. The guage is rebuilt when the counter increments.

The memory leak can be observed by opening devtools, going to the memory tab, pressing GC, then Snapshot to view current memory state, hitting the counter increment button a bunch of times, then GC/Snapshot again to view the new memory state.

The number of chart/guage objects in memory increases linearly with the counter.

<img width="899" alt="Screenshot 2020-01-03 at 16 12 52" src="https://user-images.githubusercontent.com/171523/71734919-f7e73500-2e44-11ea-95a7-57d0ac0d5dfa.png">

Screenshot show result of rebuild 45 times, I've tested up to 200 rebuilds and memory is still not released.

Setting enableAnimation to false fixes the issue in this demo.

**Comment by muhleder** [comment]
Demo of a memory leak in SfCartesianChart https://gist.github.com/muhleder/b34aa55a19954b15bbc50617240c98b8

Workaround for SfCartesianChart is to pass in  `key: UniqueKey()` to force disposal of the widget on rebuild. Without the unique key the dispose method on SfCartesianChart is never called.

**Comment by dharanidharandharmasivam** [comment]
Hi @muhleder ,

Greetings from Syncfusion. We have analyzed your query and we can replicate the reported issues in radial gauge and chart widgets. So, we have logged a defect report in our feedback portal. This issue fix will be available for volume 4 sp1 release, which is expected to be out at the end of January 2019, and we appreciate your patience until then.  You can track the status of the reported bugs from the below feedback link.

**Feedback:** https://www.syncfusion.com/feedback/11131

Thanks,
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @muhleder ,

Thanks for the patience. Fix for the reported issue has been included in the vol 4 sp1 release. In this, we have included the fix for the Radial gauge widget and due to some technical complexity, we are unable to include the chart widget fix. However, we have generated a custom package with the fix for chart widget which can be found below.

https://www.syncfusion.com/downloads/support/directtrac/general/ze/intermediate-198820266 

Download the chart widget package from above and refer the local package in your pubspec file. We will include the fix in our upcoming publish. Find the code snippet for referring the package locally,

```
syncfusion_flutter_charts:
    path: D:/flutter_charts/intermediate
```

To fix the radial gauge issue, kindly use the below package.
https://pub.dev/packages/syncfusion_flutter_gauges/versions/17.4.46-beta 

Thanks,
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @muhleder ,

Thanks for being patience. The reported issue has been for Radial gauge and Chart widgets and these fixes were included in the respective packages in the pub. The latest packages can be found below.

Radial gauge: https://pub.dev/packages/syncfusion_flutter_gauges/versions/18.1.36
Chart: https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.36

Thanks,
Dharani.
