### ISSUE TITLE
Feature updation request (Resource week view, Resource Header view change )

### ISSUE THREAD

**Issue by Star-Lord-76** [syncfusion/flutter-examples#698]
1) Please Include the resource header view changing like horizontal or vertical mode. 
2) Add the resource calendar view to week view and work week view.
3) Filter the resources fields like selecting only 2 resource or more and search names.

**Comment by M0in4** [comment]
up for the point n.1

**Comment by MuniappanSubramanian** [comment]
@Star-Lord-76 

As of now, the Flutter calendar does not have support for " **Horizontal Resource grouping support in the Flutter event calendar**" and we have logged a feature request for the same. We will implement this feature in any of our upcoming releases.    
   
At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.   
   
Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.   
    
You can also communicate with us regarding the open features at any time using our Feature Report page.    
   
We will prioritize the features every release based on the demands and we do not have an immediate plan to implement this feature since we committed to already planned work. So, this feature will be available in any of our upcoming releases.    
   
Please upvote these features to make this our priority. While this feature itself is important we will prioritize the features every release, based on the user demands. So, this feature will be available in any of our upcoming releases   
    
Feedback link: https://www.syncfusion.com/feedback/15067/horizontal-resource-grouping-support-in-the-flutter-event-calendar-sfcalendar  
    
If you have any more specifications/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.
