### ISSUE TITLE
Flutter web datagrid(dataGridCell.value.runtimeType)

### ISSUE THREAD

**Issue by adpmhel24** [syncfusion/flutter-examples#703]
I'm getting int even though the value was double. The issue occurs in flutter web but in other platforms it just working fine.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @adpmhel24,

Attempting the scenario with SfDataGrid version **20.3.56** by checking the **runtimeType** for **double** values and confirming that the **runtimeType** is shown correctly for the double values. I've attached a simple sample.

Sample: [sample.zip](https://github.com/syncfusion/flutter-examples/files/10009220/sample.zip)

**Comment by adpmhel24** [comment]
Hi, this is the screenshot of 2 different platforms. Web and Macos.
Please see attached screenshot for reference.

**Comment by adpmhel24** [comment]
I've tried to modify your sample and change the value to 00 after the
decimal and this was the result, please see attached screenshot.

**Comment by adpmhel24** [comment]
I've tried to modify your sample and change the value to 00 after the
decimal and this was the result, please see attached screenshot.[image:
Screen Shot 2022-11-15 at 5.07.30 PM.png]

**Comment by adpmhel24** [comment]
I've tried to modify your sample and change the value to 00 after the
decimal and this was the result, please see attached screenshot.

![Screen Shot 2022-11-15 at 5 07 30 PM](https://user-images.githubusercontent.com/40779451/202119828-396bf4bc-b74e-4d49-a8e6-6833c367ba50.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @adpmhel24,

The underlying **int** type in the **web** is similar to a subtype of **double**. It’s a double-precision value without a fractional part. In fact, **a type check on the web of the form x is int returns true if x is a double with a zero-valued fractional part**. **This is expected behavior of the Dart in the web platform**. The Dart has some differences in number semantics and implementation across platforms, particularly on the Web, where it has some larger differences to fit into the JavaScript model. This is a platform-specific behavior, also it might change in the future. Please go through the following Dart documentation.

**Dart documentation:** https://dart.dev/guides/language/numbers#types-and-type-checking 

**DartPad output:** 

![image](https://user-images.githubusercontent.com/93904422/202189179-c8c9801f-df4a-49e9-bf94-0170f3aa47f1.png)
