### ISSUE TITLE
RenderAbstractViewport

### ISSUE THREAD

**Issue by Alade5673** [syncfusion/flutter-examples#737]
Getting this error - A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.

**Comment by LavanyaGowtham2021** [comment]
The reported issue is caused by a recent upgrade to the Flutter version. To resolve this issue, upgrade the Flutter SDK to version 3.7.0, as all the Syncfusion Flutter packages have been updated to this version. 

If you are still facing the reported issue, please provide us with more information on your requirement in detail, along with screenshots/screen recordings, so that we can assist you better.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
