### ISSUE TITLE
[syncfusion_flutter_calendar]: How to fix month offsets

### ISSUE THREAD

**Issue by ziqq** [syncfusion/flutter-examples#744]
### How to fix month offsets?

<img width="375" alt="image" src="https://user-images.githubusercontent.com/20646071/222444709-fea2b803-08c3-4090-ae95-ca8289cd5828.png">

**Comment by Indumathi1195R** [comment]
ziqq,

As per the calendar behavior, when setting the ShowLeadingAndTrailingDays as False, the previous and next month's dates are not shown in the view. As per the implementation, we can’t restrict this behavior for a particular month. Empty spaces will be there when using this property, which is an expected behavior of the calendar.

We hope that this helps you. Please let us know if you need further assistance on this.

**Comment by ziqq** [comment]
@Indumathi1195R, I don't use the `showLeadingAndTrailingDays`

**Comment by IndumathiR-1995** [comment]
Hi ziqq,

Yes, you didn't use the showLeadingAndTrailingDays property. But empty spaces for the previous and next months will be there and it is an expected behavior. If possible can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by ziqq** [comment]
Hi @IndumathiR-1995,

I want to fix empty space and it is all.

**Comment by ziqq** [comment]
Any news? Any body help me?

**Comment by IndumathiR-1995** [comment]
Hi ziqq,

As per our previous update,  by using the ShowLeadingAndTrailingDays property we can hide the previous or next month dates, but empty row space will be there, which is expected behavior in calendar. Also, in calendar month cell height will be arranged based on the number of weeks and available height of calendar. We hope that this information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
