### ISSUE TITLE
Remove empty space on Bottom when showTrailingAndLeadingDates is false

### ISSUE THREAD

**Issue by quocviet1996** [syncfusion/flutter-examples#779]
![image](https://github.com/syncfusion/flutter-examples/assets/48380821/9031fe48-7dbf-4f08-a9b6-9f5772d45eb5)

So i have a calendar like this,which  only shows days in the month, so i set showTrailingAndLeadingDates to false, but i can't remove this empty space, how can i do that? Thanks.

**Comment by IndumathiR-1995** [comment]
Hi Team,

As per the calendar behavior to render the calendar we need 6 rows, using the [NumberOfWeeksInView](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/MonthViewSettings/numberOfWeeksInView.html) property we can customize it. So that the calendar month cell height will be arranged based on the number of weeks and available height of calendar. We can’t restrict this behavior for the month. Empty spaces will be there when using this property, which is an expected behavior of calendar. 

We hope that this helps you. Please let us know if you need further assistance on this.


Regards,
Indumathi R

**Comment by SourabhKumar11** [comment]
I can fix this for  u. please let me know if u interested.

**Comment by LavanyaGowtham2021** [comment]
Hi @SourabhKumar11 ,
As said earlier and as per the calendar implementation we can’t restrict this behavior for particular month. Empty spaces will be there when using this property, which is an expected behavior of calendar.
