### ISSUE TITLE
Signature pad is not working in IOS

### ISSUE THREAD

**Issue by aniket-github** [syncfusion/flutter-examples#792]
I tried to draw a star(Draw with high speed), and it fills white space with black color.

![simulator_screenshot_6AE88092-A891-46E5-9508-CBE68EEA9625](https://github.com/syncfusion/flutter-examples/assets/20373927/5e4108d9-5bc3-4b68-8137-a76646246fd6)

versions:
- syncfusion_flutter_signaturepad: ^21.2.10
```
flutter --version
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (3 weeks ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
-----------------------------------------------------
 Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

```

**Comment by aniket-github** [comment]
@davsyncfusion @SyncfusionBuild @SyncfusionKarthikeyan

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked the reported issue with [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) and have reproduced it at our end. This issue is replicated with 3.10.0 and later Flutter SDK versions because Flutter uses an impeller rendering engine for iOS by default. Disabling the impeller by following the steps mentioned in the below link can resolve your issue.



Link: https://docs.flutter.dev/perf/impeller#ios

**Comment by aniket-github** [comment]
thanks for your reply, Solution worked for me.
