### ISSUE TITLE
line chart drew timeout when there are many data，and drag the window or mouse stucked

### ISSUE THREAD

**Issue by GaoXing0608** [syncfusion/flutter-examples#805]
It will stucked when the source data is large.

If the source data are more than the screen's width, such as there are 2000 data, and the screen width is 1000, whether the some data were drew twice?

![unsmooth](https://github.com/syncfusion/flutter-examples/assets/47878271/ae58dad5-5e8d-4769-ab1b-412a374101c3)
![smooth](https://github.com/syncfusion/flutter-examples/assets/47878271/0388149d-b2de-4750-8dd4-57c2e68f0ff2)

**Comment by sfHariHaraSudhan** [comment]
Hi @GaoXing0608,

In [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), while rendering large data points we prefer using [FastLine Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) instead of [Line Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) for better performance. Therefore, We recommend you to check whether the mentioned behavior is replicated when using the [FastLine Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html). With those additional details, it will be useful for us to provide the best possible solution from our end. We have also shared the User Guide documentation for the [FastLine Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) below.

UG: https://help.syncfusion.com/flutter/cartesian-charts/chart-types/fast-line-chart

Regards,
Hari Hara Sudhan. K.

**Comment by GaoXing0608** [comment]
I have replaced the LineSeries to FastLineSeries, it is unsmooth when I drag the range controller
![unsmooth2](https://github.com/syncfusion/flutter-examples/assets/47878271/9720de37-ee76-4330-ab1f-076a79aec145)

**Comment by GaoXing0608** [comment]
> Hi @GaoXing0608,
> 
> In [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), while rendering large data points we prefer using [FastLine Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) instead of [Line Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) for better performance. Therefore, We recommend you to check whether the mentioned behavior is replicated when using the [FastLine Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html). With those additional details, it will be useful for us to provide the best possible solution from our end. We have also shared the User Guide documentation for the [FastLine Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) below.
> 
> UG: https://help.syncfusion.com/flutter/cartesian-charts/chart-types/fast-line-chart
> 
> Regards, Hari Hara Sudhan. K.

How about the above problem?

**Comment by sfHariHaraSudhan** [comment]
Hi @GaoXing0608,

We suggest that you use the [enableDeferredUpdate](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/enableDeferredUpdate.html) property and the [deferredUpdateDelay](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/deferredUpdateDelay.html) property to update the dependent components with a delay. We have shared the User Guide documentation below regarding the deferred update.

UG: https://help.syncfusion.com/flutter/range-selector/range-controller#deferred-update

We have also shared the range selector with the deferred update sample below for your reference. Here, we have enabled the deferred update feature, and the chart gets updated when the thumb is dragged and held for the specified [deferredUpdateDelay](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/deferredUpdateDelay.html) duration in the [Range Selector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector-class.html). You can use the deferred update according to your needs with this reference, and if you have further queries, please get back to us.

Range Selector with deferred update: https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/sliders/range_selector/range_selector_with_zooming.dart

Regards,
Hari Hara Sudhan. K.
