### ISSUE TITLE
Timeline date picker for hijri date picker

### ISSUE THREAD

**Issue by SohybBinselm** [syncfusion/flutter-examples#806]
How is it possible to create timeline picker in the hijri calender ? 
HijriDatePickerMonthViewSettings => it doesn't have the option to customize the [numberOfWeeksInView] like the SfDateRangePicker.

**Comment by IndumathiR-1995** [comment]
Hi ,

We have logged the feature request for “**Providing a support to numberOfWeeksInView in the SfHijriDateRangePicker**”. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know once this feature is implemented. We appreciate your patience until then.   

You can also communicate with us regarding the open features any time using our Feature Report page.       

**Feedback link:**
https://www.syncfusion.com/feedback/45805/providing-a-support-to-numberofweeksinview-in-the-sfhijridaterangepicker

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.  

Regards,
Indumathi R

**Comment by SohybBinselm** [comment]
Ok thank you.

**Comment by SohybBinselm** [comment]
Any updates? @IndumathiR-1995

**Comment by IndumathiR-1995** [comment]
Hi Sohy,

We will prioritize the features every release based on the user demands and we do not have immediate plan to implement this feature since we committed with already planned work. Please upvote this feature to make this our priority. We will implement and include this feature in our any of upcoming release. We will let you know once release roll out. We appreciate your patience until then.

Regards,
Indumathi R
