### ISSUE TITLE
SfCircularChart: DoughnutSeries how can i add spacing/ white lines between sections. Flutter

### ISSUE THREAD

**Issue by Samamoah** [syncfusion/flutter-examples#811]
I see this in the documentation. How can I achieve this with the spacing/lines between each section. I don't want to use explode
![doughnut_colormapping](https://github.com/syncfusion/flutter-examples/assets/38361238/1e958bff-a66d-45a4-9a00-47b4bd1534ab)

**Comment by sfHariHaraSudhan** [comment]
Hi @Samamoah,

You can achieve your mentioned requirement by using the [stroke color](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartPoint/strokeColor.html) property and [stroke width](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartPoint/strokeWidth.html) property of the [Doughnut Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DoughnutSeries-class.html) and we have shared the sample code link below for the Doughnut Series Color Mapping in the sample browser for your reference.

Sample Code: [Flutter Sample in Github for Doughnut Series Color Mapping](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/circular_charts/chart_types/doughnut/doughnut_with_color_mapping.dart).
SB: https://flutter.syncfusion.com/#/circular-charts/chart-types/doughnut/color-mapping

In this sample, to show the line gap between the segments, the [stoke color](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartPoint/strokeColor.html) property and [stroke width](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartPoint/strokeWidth.html) property is used instead of using the [explode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/explode.html) property. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by Samamoah** [comment]
Thank you
