### ISSUE TITLE
Unable to add Table in existing pdf page (Not as new page in pdf document ) in flutter

### ISSUE THREAD

**Issue by dalu547** [syncfusion/flutter-examples#812]
Iam trying add table in existing pdf page, but iam unable to add. (It is adding as new page in pdf document)

below is my code, please help me out in this scenario

final PdfDocument document =
PdfDocument(inputBytes: File(_file!.path).readAsBytesSync());

**final PdfPage pdfPage = document.pages[0];** // adding in first page
//Create a PdfGrid class
PdfGrid grid = PdfGrid();

//Add the columns to the grid
grid.columns.add(count: 3);

//Add header to the grid
// grid.headers.add(1);

//Add the rows to the grid
// PdfGridRow header = grid.headers[0];
// header.cells[0].value = 'Sign';
// header.cells[1].value = 'Sign';
// header.cells[2].value = 'Sign';

PdfGridRow row = grid.rows.add();
row.cells[0].value = 'Sign';
row.cells[1].value = 'Sign';
row.cells[2].value = 'Sign';
//Add rows to grid
PdfGridRow row1 = grid.rows.add();
row1.cells[0].value = 'xxxxxxx';
row1.cells[1].value = 'xxxxxxx';
row1.cells[2].value = 'xxxxxxxx';

PdfGridRow row2 = grid.rows.add();
row2.cells[0].value = 'Lead';
row2.cells[1].value = 'Manager';
row2.cells[2].value = 'Manager';
//Set the grid style
grid.style = PdfGridStyle(
cellPadding: PdfPaddings(left: 2, right: 3, top: 4, bottom: 5),
backgroundBrush: PdfBrushes.white,
textBrush: PdfBrushes.black,
font: PdfStandardFont(PdfFontFamily.helvetica, 25));

//Draw the grid
grid.draw(
page: pdfPage,
bounds: const Rect.fromLTWH(0, 0, 0, 0));

// grid.draw(page: page);

String tableFilePath = '/storage/emulated/0/Download/greensign_watermark_table.pdf';
//Save and dispose the PDF document
File(tableFilePath).writeAsBytes(await document.save());
document.dispose();

Iam getting runtime error as 
_"E/flutter (16417): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value"_

**Comment by irfanajaffer** [comment]
The fix for the reported issue "Null check error occurs while drawing PDF grid in a loaded page" has been included in our weekly release v22.2.11.



Kindly use the following link to refer to latest package,

[https://pub.dev/packages/syncfusion_flutter_pdf/versions](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fpackages%2Fsyncfusion_flutter_pdf%2Fversions&data=05%7C01%7Csanthiya.narayanan%40syncfusion.com%7C2b76a7ea842548fad22208dba86faebc%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638288969839124499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VyA5XKgRBbtPiz8Dg3c%2BURZ3sHEI3boOP35t%2F7KTdfk%3D&reserved=0)
