### ISSUE TITLE
I just import the syncfusion_flutter_charts in my flutter project it gives me errors? Previous its working but now its giving error.

### ISSUE THREAD

**Issue by sachhu411288** [syncfusion/flutter-examples#820]
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/base/chart_base.dart:2420:44: Error: 'PointerPanZoomUpdateEvent' isn't a type.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/base/chart_base.dart:2420:19: Error: No named parameter with the name 'onPointerPanZoomUpdate'.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                  ^^^^^^^^^^^^^^^^^^^^^^
../../Documents/flutter/packages/flutter/lib/src/widgets/basic.dart:6053:9: Context: Found this candidate, but the arguments don't match.
  const Listener({
        ^^^^^^^^
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/user_interaction/zooming_panning.dart:1021:25: Error: 'PointerPanZoomUpdateEvent' isn't a type.
    } else if (event is PointerPanZoomUpdateEvent) {
                        ^^^^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

I tried latest version also.

My flutter configuration--
Flutter version 3.14.0-14.0.pre.423 on channel master at /Users/sachinjain/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 30a9f99bc8 (45 minutes ago), 2023-09-21 11:49:29 -0700
    • Engine revision 78c1ad249b
    • Dart version 3.2.0 (build 3.2.0-187.0.dev)
    • DevTools version 2.28.0-dev.12

**Comment by sfHariHaraSudhan** [comment]
Hi,

We have checked the onPointerPanZoomUpdate callback in the Listener widget by implementing a simple sample using the current version of the Flutter SDK with the Master channel based on the provided configuration, and unfortunately, we are unable to replicate the mentioned exception.

However, we suspect that the mentioned exception might have occurred due to some cache, and we recommend that you check by clearing the cache using the below-mentioned methods:

1. In the Flutter terminal, add the "**flutter pub cache clean**" command to clear all the cache.
2. Close the running application and then add the "**flutter clean**" command.
3. Afterwards, add the "**flutter pub get**" command to get all the dependencies in the pubspec.yaml file.

If you still face the mentioned exception even after clearing the cache, then kindly share with us some detailed information regarding when and where the exception occurs, along with any snapshots or recordings. With that additional information, it will be very useful for us to find a possible solution from our end.

Regards,
Hari Hara Sudhan. K.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this

**Comment by liannguyenrapp** [comment]
I'm getting the same issue
```
../../../../../.pub-cache/hosted/pub.dartlang.org/fl_chart-0.40.6/lib/src/chart/pie_chart/pie_chart.dart:42:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../fvm/versions/3.0.0/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
../../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/base/chart_base.dart:2420:44: Error: 'PointerPanZoomUpdateEvent' isn't a type.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/base/chart_base.dart:2420:19: Error: No named parameter with the name 'onPointerPanZoomUpdate'.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                  ^^^^^^^^^^^^^^^^^^^^^^
../../../../../fvm/versions/3.0.0/packages/flutter/lib/src/widgets/basic.dart:6053:9: Context: Found this candidate, but the arguments don't match.
  const Listener({
        ^^^^^^^^
../../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/user_interaction/zooming_panning.dart:1021:25: Error: 'PointerPanZoomUpdateEvent' isn't a type.
    } else if (event is PointerPanZoomUpdateEvent) {
```

When I try to trace the code back, the `PointerPanZoomUpdateEvent` is highlighted as an unknown type.

![image](https://github.com/user-attachments/assets/b22b69f8-36c1-4f89-bc8f-831a17175ddf)

**Comment by ZeroJsus** [comment]
same error in flutter sdk 3.0.1, syncfusion_flutter_charts sdk 21.2.4
