### ISSUE TITLE
</Error>

### ISSUE THREAD

**Issue by PmPPolska** [syncfusion/flutter-examples#843]
(:hhttps://www.qwant.com?l=pl&client=brz-samsung&theme=1&hc=0&hti=0&vt=1&b=1&s=1&locale=en_IE&home=daily&si=0&c=blue&ch=random&eco# _suggest=1__ttps://mobile-webview.gmail.com/780223503/blocked].md

**Comment by LavanyaGowtham2021** [comment]
Hi @PmPPolska ,

We have checked your query at our end and as we are not able to understand what your proposing as your requirement, we kindly request you to share us with more information on your requirement in detail along with screenshots/screenrecordings so that it will help us assist you in a better way.
