### ISSUE TITLE
Cartesian Chart covering Full Screen Width

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#88]
I'd like for the cartesion chart to fill the entire screen width so that the plotted line goes from the left screen edge to the right screen edge. Even if I place the SfCartesianChart in a Container and set the container width to the screen width (MediaQuery.of(context).size.width), the line does not reach the edge of the screen on either end, shown below.

I think this would improve how it looks, especially considering the cutoff behavior you can see on right side of the plotted line (where it becomes more narrow).

![image](https://user-images.githubusercontent.com/50309714/77217912-842bfe80-6afc-11ea-85ef-677214ac76f4.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Thanks for using our Syncfusion Flutter charts widget. We have analyzed your query and we would like to let you know that by default, the margin is set to 10 for all the sides. Therefore, there is space in your chart. If you don’t want the space, kindly specify to zero, so that the chart will occupy the entire space of the container widget. Find the code snippet below,

> 
      SfCartesianChart(
                      plotAreaBorderWidth: 0,
                      margin: EdgeInsets.fromLTRB(0,10,0,10),
                      // Other configurations
                    )

The sample for reference can be found below,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/issue_88-769618691 

And regarding the cut off behavior, when the series goes out of plot area, it will not be visible and this is our default behavior. However, you specify the rangePadding as additional to overcome this scenario.  Find the code snippet below.

> 
    SfCartesianChart(
                      primaryXAxis: DateTimeAxis(
                          rangePadding: ChartRangePadding.additional),
                    )

You can also create incidents using the below link, this will be helpful in better follow up.
https://www.syncfusion.com/support/directtrac/incidents 

Thanks,
Dharani.
