### ISSUE TITLE
Column Chart - Don't Clip Columns

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#93]
I made a 100% Stacked Column Chart and enabled panning. The x-axis is a CategoryAxis with ~13 columns, but I want the view plot to initially show 7 of the far right columns and allow the user to pan to see the rest.

The problem is that the plot initializes in a position where the column on the left is partially clipped off the screen.

To make it show only 7 initially, I tried these methods:

- set visibleMaximum of x-axis to 7. This results in the image below where it clips the leftmost column.

- set zoomFactor of x-axis to a lower value. This seems to work, but I'm not not sure it ensures that the leftmost column does not clip on other devices with slightly different screen width.

Is there a better solution to this?

![image](https://user-images.githubusercontent.com/50309714/77280262-3a791a80-6c9a-11ea-876c-f1cba9ae49b9.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. We have analyzed your scenario and your requirement can be achieved using the visibleMaximum property itself. In the category axis, if you wish to view only the first seven data, then you can specify the visibleMaximum as 6.5 so that the other points will not get clipped. We have prepared a sample based on the above scenario in which we have 10 data and we have shown only the first 7 data.

We have attached a sample for your reference which can be found below.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/issue_93-1604356409 

Screenshot:
<img width="242" alt="issue_93" src="https://user-images.githubusercontent.com/19346074/77291958-4cdc6e00-6d05-11ea-8711-28edab8c60f4.PNG">

You can also create incidents using the below link, this will be helpful in better follow up.
https://www.syncfusion.com/support/directtrac/incidents 

Thanks,
Dharani.
